### ISSUE TITLE
Values missing due to `omitempty`

### ISSUE THREAD

**Issue by zemirco** [twitchtv/twirp#100]
First of all, thank you for this package! It is awesome and super simple to use. Great job!

I've got my message definition

```
message Points {
  int32 team_a = 1;
  int32 team_b = 2;
}
```

which is translated into a Go type.

```
type Points struct {
	TeamA int32 `protobuf:"varint,1,opt,name=team_a,json=teamA" json:"team_a,omitempty"`
	TeamB int32 `protobuf:"varint,2,opt,name=team_b,json=teamB" json:"team_b,omitempty"`
}
```

I'm using JSON to communicate between browser and twirp backend. Now I've got a match where `team_a = 2` and `team_b = 0`. In the browser the value for `team_b` is missing since `0` is the zero value for `int`. Those are left out due to the `omitempty` flag.

> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.

That's a bit annoying :)

Any ideas how to make it work? How do you handle those cases at Twitch?

**Comment by rhysh** [comment]
Hi @zemirco — the json field tags are a bit of a red herring. What you're seeing is part of how proto3 messages are encoded: default values aren't sent. The [proto3 guide](https://developers.google.com/protocol-buffers/docs/proto3#default) says that when a message is deserialized you can't tell whether zero values were set or not, and it uses that to save space/time on the wire by not sending zero values of primitives in the first place.

The way to work around this is by using the "wrapper" message types defined in [google/protobuf/wrappers.proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/wrappers.proto). The types defined there are known to the jsonpb package and get encoded as primitive values, not as nested messages.

```
import "google/protobuf/wrappers.proto";

message Points {
  google.protobuf.Int32Value team_a = 1;
  google.protobuf.Int32Value team_b = 2;
}
```

Keep in mind that Twirp's json encoding is done with the golang/protobuf jsonpb package rather than by encoding/json, and that the jsonpb.Marshaler has `OrigName` set. That means that the json field names will match the protobuf field names rather than being a weird lowerCamelCase version (yay), but that the `json_name` annotation will be ineffective.

**Comment by zemirco** [comment]
Thanks for the quick reply.

With `google.protobuf.Int32Value` I'd have to use the `.Value` workaround. For now I simply use

```
sed -i "s/,omitempty//" service.pb.go
```

A bit hacky but works for me.

**Comment by spenczar** [comment]
Yeah, this is the way the JSON format for protobuf data works. In protobuf, there is no distinction between a zero value and an unset value, so what you're seeing is entirely correct. `omitempty` is not really what's doing this; it's the way `jsonpb` works and is defined by a pretty thorough [specification](https://developers.google.com/protocol-buffers/docs/proto3#json).

If you want to distinguish between an unset value and a zero value, you need to use the wrapper types that @rhysh linked to.

@zemirco, could you say a little more about how this is affecting you? Ideally, with Twirp, the serialization of the request and response are just implementation details. If you're using a generated JavaScript client, you shouldn't need to care about the fact that the JSON encoding skips zero values.

**Comment by zemirco** [comment]
I'm not using one of the generated JavaScript clients. Wanted to keep it simply and just use `fetch`. e.g.

```
    fetch('twirp/trpc.Haberdasher/GetMatchesPoints', {
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST',
      body: JSON.stringify({...})
    })
    .then(response => {
      return response.json()
    })
    .then(data => {
      console.log(data)
    })
```

Using the wrapper types work fine for the frontend (zero values are now included) but in my backend my model now looks like this.

```
type Points struct {
	TeamA *google_protobuf1.Int32Value `protobuf:"bytes,1,opt,name=team_a,json=teamA" json:"team_a,omitempty"`
	TeamB *google_protobuf1.Int32Value `protobuf:"bytes,2,opt,name=team_b,json=teamB" json:"team_b,omitempty"`
}
```

Using it with some data makes it a bit more complicated.

```
	p := &Points{
		TeamA: &wrappers.Int32Value{
			Value: a,
		},
		TeamB: &wrappers.Int32Value{
			Value: b,
		},
	}
```

**Comment by zemirco** [comment]
I wrote a code generator for plain JavaScript without any dependencies. Check it out at https://github.com/zemirco/protoc-gen-twirp-es. It's my first time writing a code generator for protobuf so please by nice :smiley: I'm very thankful for feedback.

It's actually pretty simple. Here is my `.proto` file

```
message Player {
  string hash_id = 1;
  int32 user_id = 2;
  string first_name = 3;
  string last_name = 4;
}

service Haberdasher {
  rpc GetPlayer(google.protobuf.Int32Value) returns (Player);
}
```

Here is the generated code

```js
const GetPlayer = async (input) => {
  const res = await fetch('twirp/trpc.Haberdasher/GetPlayer', {
    headers: {
      'Content-Type': 'application/json'
    },
    method: 'POST',
    body: JSON.stringify(input)
  })
  const data = await res.json()
  const Player = {
    hash_id: data.hash_id || "",
    user_id: data.user_id || 0,
    first_name: data.first_name || "",
    last_name: data.last_name || ""
  }
  return Player
}

export {GetPlayer}
```

As you can see every field is now included in the result. If the field is `undefined` the zero value is used. This way you can always be sure to get some value.

The indentation (in the resulting file) is a bit off but that's OK for now. It also works for nested messages and arrays. In your code you simply use it like this.

```js
import {GetPlayer} from  './service'

const player = await GetPlayer(1)
```

That's pretty sweet now. Thank's for building Twirp!
