### ISSUE TITLE
google/protobuf/empty.proto wrong import path

### ISSUE THREAD

**Issue by zemirco** [twitchtv/twirp#104]
simple `.proto` file

```proto
syntax = "proto3";

package hello;

import "google/protobuf/empty.proto";

service Hello {
  rpc SayHello(SomeMessage) returns (google.protobuf.Empty);
}
```

Twirp generates code like this

```go
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"

SayHello(context.Context, *SomeMessage) (*google_protobuf.Empty, error)
```

However `Empty` isn't part of the `wrappers` package. The correct import path is `"github.com/golang/protobuf/ptypes/empty"`.

The generated file should look like this

```go
import "github.com/golang/protobuf/ptypes/empty"

SayHello(context.Context, *SomeMessage) (*empty.Empty, error)
```

**Comment by zemirco** [comment]
@spenczar Thank you for looking into this. I've tried generating the files on Mac and on Linux. I'm getting the same error on both platforms.

Here is my `empty.proto` from `/usr/local/include/google/protobuf/`

```proto
syntax = "proto3";

package google.protobuf;

option csharp_namespace = "Google.Protobuf.WellKnownTypes";
option go_package = "github.com/golang/protobuf/ptypes/empty";
option java_package = "com.google.protobuf";
option java_outer_classname = "EmptyProto";
option java_multiple_files = true;
option objc_class_prefix = "GPB";
option cc_enable_arenas = true;

// A generic empty message that you can re-use to avoid defining duplicated
// empty messages in your APIs. A typical example is to use it as the request
// or the response type of an API method. For instance:
//
//     service Foo {
//       rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);
//     }
//
// The JSON representation for `Empty` is empty JSON object `{}`.
message Empty {}
```

Maybe it's because I've got other well known types in my `.proto` file? Could you try this modified example? In this case I'm using `google.protobuf.StringValue` instead `SomeMessage`.

```proto
syntax = "proto3";

package hello;

import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

service Hello {
  rpc SayHello(google.protobuf.StringValue) returns (google.protobuf.Empty);
}
```

**Comment by spenczar** [comment]
Thanks, @zemirco, I can indeed replicate your bug when I import both `google/protobuf/wrappers.proto` and `google/protobuf/empty.proto`. I'll dig in further now.

**Comment by spenczar** [comment]
@zemirco, #107 proposes a fix. You could try branch `alias_imports_correctly` on your project, if you like.

**Comment by zemirco** [comment]
Thank you! Works fine now and I can remove my custom `Empty` message.

**Comment by zunaira1231** [comment]
Can u please tell me how u resolved this error @zemirco

**Comment by chuwt** [comment]
@zunaira1231 when you download protoc, there also a dir names include, copy that dir to your workspace(or somewhere you  want), then add -I=include when you run protoc to generate protobuf
