### ISSUE TITLE
Context with value isn't working

### ISSUE THREAD

**Issue by s4kibs4mi** [twitchtv/twirp#108]
I have added value with context in client side but that isn't being sent to server. What is the proper way to doing this. I have tried context.WithValue and twirp.HttpRequestsHeader no one is working.

**Comment by spenczar** [comment]
@s4kibs4mi Context values are not sent automatically between client and server. If you want to communicate a value from client to server, you should add it to the protobuf message definition that's used for the request type of the RPC.

This makes sure that the message definition correctly shows the complete set of arguments expected, and makes it easier to work across language boundaries, so it's by design.

**Comment by s4kibs4mi** [comment]
@spenczar can you please guide me how to define it in proto ? What I am doing now is setting header value and I am catching it in http request using a middleware and from there forwarding to twirp handler. So my question is what is the proper way to authenticate something for each request like we do in RESTful.  And if I am getting header value in http middleware whyn't it is being passed to twrip middleware !!!

**Comment by spenczar** [comment]
@s4kibs4mi I think you're looking for `twirp.WithHTTPRequestHeaders` to set the header in the client, as described in https://twitchtv.github.io/twirp/docs/headers.html#send-http-headers-with-client-requests. Then, you can pull it out of the request with middleware, as you expect.

**Comment by s4kibs4mi** [comment]
@spenczar I tried this as well, but problem is the headers are not coming in twirp middleware directly. So I am parsing them in http middleware and adding them in context to send them to twirp middleware. I am using a mix of chi.Router with twirp as handler.

**Comment by spenczar** [comment]
@s4kibs4mi Right, that's the expected flow. The headers don't appear in Twirp request contexts automatically.

**Comment by s4kibs4mi** [comment]
@spenczar fine. But if I add headers in context from client using `twirp.WithHTTPRequestHeaders()`, it should be visible in middleware context so in server side it's parseable using `twirp.HTTPRequestHeaders()`, isn't it ?

**Comment by spenczar** [comment]
@s4kibs4mi No, `twirp.HTTPRequstHeaders(ctx)` is only used internally by the generated client code to actually send the headers you've set, and is not used by the server. You have to explicitly use middleware (like you've done) if you need request headers to be available in each method.

We've tried to document this in https://twitchtv.github.io/twirp/docs/headers.html. Maybe there is room to improve documentation here. What led you towards using `twirp.HTTPRequestHeaders`?
