### ISSUE TITLE
Turn the example into its own repository that we can clone

### ISSUE THREAD

**Issue by hugows** [twitchtv/twirp#11]
Hi!

A minor suggestion: make it so that the example (https://github.com/twitchtv/twirp/wiki/Usage-Example:-Haberdasher) is in a separate repo, that we can git clone, cd into and follow simple instructions to have a running server and client.

Its just an idea, but I've noticed this on other projects and makes everything super easy for beginners (even though Twirp isn't exactly for beginners, coming from Twitch a lot of people might want to play with it).

Cheers!

**Comment by spenczar** [comment]
This is a great idea, and we should do it for sure. We'll set something up within the next week.

**Comment by while-loop** [comment]
Any progress on this creating the example repo? I'll be glad to set up the example Haberdasher code

**Comment by spenczar** [comment]
This is now up and running at https://github.com/twitchtv/twirp-example. Good idea!
