### ISSUE TITLE
iOS client

### ISSUE THREAD

**Issue by zboralski** [twitchtv/twirp#118]
is anyone working on a iOS client generator?

**Comment by fritzherald** [comment]
@zboralski I'm working on an [RxSwift](https://github.com/ReactiveX/RxSwift)-based iOS client as part of a react-native client library (likely to soon become a catch-all RxTwirp library with clients for swift, java, js, and react-native) — current effort is focused on supporting the experimental streaming-download twirps that are in development (see #70), but it's working for non-streaming calls as well. The code is WIP but you can get an idea of the general approach by checking out [gnarbox/react-native-twirp/ios/GBXTwirp.swift](https://github.com/gnarbox/react-native-twirp/blob/5c9d5cfd982e252d90c7d097ef566125020ec836/ios/GBXTwirp.swift).

I'm just in the process of migrating from a [protobuf.js](https://github.com/dcodeIO/protobuf.js)-based generator to a setup based on [protoc-gen-gotemplate](https://github.com/moul/protoc-gen-gotemplate) to try to provide an easier interface for customizing/extending the generated code, I should have something ready to share in about a week or so and will post here when it's at a point where it's all up and running. Feel free to hit me up on the gophers slack ("@fritzherald") if you want to get into the weeds and discuss some of the finer points

**Comment by spenczar** [comment]
I'm closing this as not-really-a-bug - the Gophers slack is the best place for questions like this. Thanks!
