### ISSUE TITLE
twirp context keys can conflict with client code's context keys.

### ISSUE THREAD

**Issue by RoarkeRandall** [twitchtv/twirp#119]
Here's the context keys that twirp uses internally:

```
// Package contextkeys stores the keys to the context accessor
// functions, letting generated code safely set values in contexts
// without exposing the setters to the outside world.
package contextkeys

type contextKey int

const (
	MethodNameKey contextKey = 1 + iota
	ServiceNameKey
	PackageNameKey
	StatusCodeKey
	RequestHeaderKey
	ResponseWriterKey
)
```

Are those context keys safe? seems pretty easy for a conflict to occur. I’ve read to use an empty struct for context keys.

**Comment by spenczar** [comment]
These are safe. Context keys are `interface{}`s, which are stored as a pair of (type, pointer-to-value).

Here, the `contextKey` type is unexported, which means client code could never create a colliding (type, pointer-to-value) pair.

Here's a demonstration that a typed integer and an untyped integer with the same value do not collide: https://play.golang.org/p/ONFI2igs7QI

See https://research.swtch.com/interfaces for more on how interfaces work in Go.
