### ISSUE TITLE
Generated code will not compile if the service defined in protobuf definition has a method defined with the same name.

### ISSUE THREAD

**Issue by darren-west** [twitchtv/twirp#123]
Hi,

While evaluating twirp I came across a small issue. I created a simple Protobuf service definition that echoes a message. I decided to call the service Echo with a method of Echo for simplicity. I found that the generated code did not compile. 

Protobuf example below:

```protobuf
syntax = "proto3";

package twitch.twirp.echo;
option go_package = "api";

service Echo{
    rpc Echo(Message) returns (Message) {}
}

message Message {
    string Value = 1;
}

```

Although this is probably a rare case, I looked into it and its because it uses an embedded struct in the generated server struct. 

I will be creating a PR with the fix. 

Thanks,
Darren

**Comment by spenczar** [comment]
Fixed in #124, release v5.4.2.
