### ISSUE TITLE
public PackageName and ServiceName as constant (like PathPrefix)

### ISSUE THREAD

**Issue by nvcnvn** [twitchtv/twirp#128]
I'm writing a custom middle-ware function for propagate tracing context from HTTP headers.  
Hooks cannot be use in my case because the context not contains any headers.  
Currently I use _PathPrefix_ const as the root span... which is OK but it seem better to have PackageName and ServiceName since they already properly injected to the context.

Something like this:  
```go
const HaberdasherPathPrefix = "/twirp/twirp.example.haberdasher.Haberdasher/"
const HaberdasherPackageName = "twirp.example.haberdasher"
const HaberdasherServiceName = "Haberdasher"

func (s *haberdasherServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, HaberdasherPackageName)
	ctx = ctxsetters.WithServiceName(ctx, HaberdasherServiceName)
```

**Comment by spenczar** [comment]
@nvcnvn Are you trying to _set_ values on the response headers, or _get_ values from the request headers?

If you're trying to set response headers, I think you should be able to do this with `ServerHooks` by using [twirp.SetHTTPResponseHeader](https://godoc.org/github.com/twitchtv/twirp#SetHTTPResponseHeader):

```go
hooks := &twirp.ServerHooks{
  RequestRouted: func(ctx context.Context) (context.Context, error) {
    pkg, _ := twirp.PackageName(ctx)
    svc, _ := twirp.ServiceName(ctx)
    method, _ := twirp.MethodName(ctx)

    h := make(http.Header)
    h.Set("X-Tracing-Server", pkg + ":" + svc + ":" + method) // or whatever
    twirp.SetHTTPResponseHeader(ctx, h)
  },
}
```

If you're trying to read request headers, you can do it with HTTP middleware:

```go
var tracingIDCtxKey = new(int)

func TracingID(ctx context.Context) string {
  v, _ := ctx.Value(traceingIDCtxKey).(string)
  return v
}

func WithTracingID(base http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    reqID := r.Header.Get("X-Tracing-Request-ID")
    ctx := context.WithValue(r.Context(), traceHeaderCtxKey, reqID)
    r = r.WithContext(ctx)
    base.ServeHTTP(w, r)
  })
}
```

Could you say more about what you are trying to do? I hope it is possible already.

**Comment by nvcnvn** [comment]
Sorry, I found myself confusing with my original example:D
In your example of reading request headers with HTTP middleware, for some reason I need the service name.

```go
func WithTracingID(base http.Handler, serviceName string) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    spanCtx, _ := b3propagation.SpanContextFromRequest(req)
    ctx, _ := trace.StartSpanWithRemoteParent(req.Context(), serviceName, spanCtx)
    req = req.WithContext(ctx)
    base.ServeHTTP(w, r)
  })
}

haberdasherHandler := haberdasher.NewHaberdasherServer(&haberdasherserver.Server{}, nil)
// good if we can have HaberdasherServiceName here... maybe
http.ListenAndServe(":9990", WithTracingID(haberdasherHandler, haberdasherserver.HaberdasherPathPrefix))
```
I just think maybe the service name and package name can be exposed,

**Comment by dpolansky** [comment]
It seems like you should be able to extract the trace ID from the HTTP request header within HTTP middleware, and then create a new `context.Context` value that contains that data. At that point, a ServerHooks implementation could read that trace ID and metadata about the Twirp RPC from the context value in order to create a new trace span. Please feel free to comment on this issue if this needs additional discussion.
