### ISSUE TITLE
how to keep the .proto files ‘servcie’ name like ‘User_backstage’ in 'UserBackstagePathPrefix'

### ISSUE THREAD

**Issue by Michael2008S** [twitchtv/twirp#150]
I user the define my service ：
```go
// User service handles user crud
service User_backstage {
    // Delete deletes a user
    rpc Delete(IDReq) returns(MessageResp);
}
```
The  service  name is  `User_backstage`.

And I gen the .twirp.go file like below:
```go
// UserBackstagePathPrefix is used for all URL paths on a twirp UserBackstage server.
// Requests are always: POST UserBackstagePathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const UserBackstagePathPrefix = "/user.UserBackstage/"

func (s *userBackstageServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
.....
	switch req.URL.Path {
	case "/user.UserBackstage/Create":
		s.serveCreate(ctx, resp, req)
		return
	case "/user.UserBackstage/List":
		s.serveList(ctx, resp, req)
		return

```
I want to keep the path look like  `"/user.User_backstage/"`

How Can I do that ?

And the swagger docs gen like this:
![image](https://user-images.githubusercontent.com/1240769/53385144-630be380-39b8-11e9-8355-5c6eb28fc8d2.png)

It can't request the api.

**Comment by dpolansky** [comment]
Hi @Michael2008S,

`protoc-gen-go` generates Go types for protobuf service and message names using Camel case (even if you define your names using Snake case). The protobuf style guide also [explicitly recommends](https://developers.google.com/protocol-buffers/docs/style) that you define message and service names using Camel case.

You could fix the issue by changing the service name (if possible), or by having the swagger generator maintain compatibility with how Twirp generates URL paths for service names. One of Twirp's design philosophies is to avoid unnecessary configuration, so we would prefer to avoid making the URL path configurable without justification.

**Comment by dpolansky** [comment]
I am closing this issue for now. We are happy to re-open this if you think the issue needs more discussion.
