### ISSUE TITLE
Improve installation process to pin external dependencies better

### ISSUE THREAD

**Issue by peter-edge** [twitchtv/twirp#152]
Sort of a two-potential-solution issue but:

Here's the problem: I want to be able to install `protoc-gen-twirp` and `protoc-gen-twirp_python` for a specific version, and with the external dependencies on their correct version. Right now, the dependencies are specified via `Gopkg.toml`, which means in https://github.com/uber/prototool/blob/e49240f4fae214a1438d8dbce7c3ba7ce658ec03/Dockerfile#L59 I have to:

1. Clone the repository at a specific tag
2. `dep ensure`
3. `go install`

The instructions right now say to `go get` the binaries, but this will ignore external dependency versions since they are not specified with a `go.mod` file.

Moving to Golang Modules will admittedly be tough, since Twirp is on v5, and this would require import paths to be `github.com/twitchtv/twirp/v5`, but this is one solution, as then `go get` would respect the dependencies in a new `go.mod` file.

The other option (which is probably universally preferable, since it doesn't require `go` to be installed) would be to release binaries for at least Darwin/Linux and x86_64 as part of GitHub Releases.

Examples:

https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.8.2
https://github.com/grpc/grpc-web/releases/tag/1.0.3
https://github.com/uber/prototool/releases/tag/v1.3.0

If choosing the suffixes, I would argue to match `uname -s` and `uname -m` to make this easy in scripts, ie `Darwin-x86_64` and `Linux-x86_64`, but just my opinion there.

https://github.com/goreleaser/goreleaser seems to be the newfangled way people are doing this, but I haven't adopted it yet.

**Edit**: Having played with the build, I just realized that `vendor` is still checked in, so `go get` is actually OK right now. You're likely going to want to move away from `vendor` being checked in as Golang Modules become more prevalent, however - I used to check in `vendor` myself but the community is decidedly moving away from this with all the recent updates.

**Comment by spenczar** [comment]
Thanks for writing this and providing some options.

My understanding is that the core thing here is that you'd like external dependencies to be correctly pinned when installing protoc-gen-twirp. As you say, `vendor` is solving that for us today, but it would be nice to move away from that as modules become the standard.

Binary releases appear to resolve a slightly different issue, which is to provide protoc-gen-twirp to platforms without requiring a proper Go build toolchain - also seems useful, but seems separable.
