### ISSUE TITLE
Add Twirp/twitchtv logo to Docusaurus

### ISSUE THREAD

**Issue by co16353sidak** [twitchtv/twirp#155]
Hey,
So at [Docusaurus](https://github.com/facebook/Docusaurus), there is work going on to list and display users/projects that have used Docusaurus to create the documentation for the said project.

Twirp being such a project, I would love to add it to the user's page.
Hopefully you guys will be interested for the same. I have includes some links for the same.

Hope to get a positive go ahead.

[Docusaurus Website](http://docusaurus.io/en/)
[User's Page](https://docusaurus.io/en/users)

For reference: facebook/Docusaurus#1080

**Comment by spenczar** [comment]
Hi! I'm good with this personally, but it's not really my call to make, since Twitch's name is attached to Twirp. Let me see if I can find an answer for you from the right Twitch people, and I'll get back to you - no promises on how fast that will be though, you know how bureaucracy can be :)

**Comment by co16353sidak** [comment]
@spenczar It's alright, time is not an issue but please do keep me informed.

**Comment by spenczar** [comment]
@co16353sidak Alright, got the greenlight for you to use the Twirp logo (https://github.com/twitchtv/twirp/blob/master/logo.png). Please don't use the Twitch logo, though, I haven't gotten that cleared and I think the bar would be a lot higher.

**Comment by co16353sidak** [comment]
Awesome, @spenczar,
Please don't close this issue until the logo is clear and visible on the page as I will be using this thread for communicating with you as to how the logo will display and everything.

**Comment by co16353sidak** [comment]
Hey, @spenczar Is it possible to have a svg format for the logo? This is done because so as to make the logo to be scalable on the website.

if not then png will do.

**Comment by spenczar** [comment]
I'm afraid all I've got is PNGs, but here's the original in full size, in case that helps:
![logo_black](https://user-images.githubusercontent.com/880413/54153235-5053ce80-43fc-11e9-9a2a-c076090c4bf9.png)

**Comment by co16353sidak** [comment]
Everything is set up @spenczar, the logo has been added although it will take some time to reflect the changes on the main website, I have linked a preview build for you to view the logo.

https://deploy-preview-1275--docusaurus-preview.netlify.com/en/users

hopefully everything is fine, thank you for your assistance in the manner. 🎉

**Comment by dpolansky** [comment]
Closing this for now. Thanks @co16353sidak
