### ISSUE TITLE
Add the Twirp logo in the official documentation.

### ISSUE THREAD

**Issue by co16353sidak** [twitchtv/twirp#157]
The documentation right now could look much more amazing if we added the twirp logo to it on the main page which opens when we click on the link on the repo.
currently this is displayed.
Would love to work on this as well.

<img width="1265" alt="Screenshot 2019-03-11 at 10 04 50 PM" src="https://user-images.githubusercontent.com/35738138/54140567-e95d0680-4449-11e9-9248-615009833e60.png">

According to me the twirp logo would look good just below or above the `Meet Twirp` heading.

url: 
https://twitchtv.github.io/twirp/docs/intro.html

**Comment by spenczar** [comment]
Sure, this sounds nice. I'm not sure how to actually do it, though, within Docusaurus's framework. I'd welcome the improvement!

**Comment by co16353sidak** [comment]
@spenczar Docusaurus does supports markdown, so I think we can link an uploaded image on the docs page. I will have a look and get back to you.

P.S :- it does the same on its documentation page.

**Comment by co16353sidak** [comment]
I went through the files and I can see that in the `intro.md` file, we can add a markdown for the twirp logo? how does that sound ?

**Comment by spenczar** [comment]
I'd really like it in the top left corner, as a logo, rather than baked into one of the posts. Is that possible?

**Comment by co16353sidak** [comment]
Yes I think so, let me go for a few iterations and then if you will welcome a PR you can tell me what you think ?
