### ISSUE TITLE
Proposal: Add PathPrefix method to generated TwirpServer type

### ISSUE THREAD

**Issue by gorzell** [twitchtv/twirp#158]
I ran into some challenges working on code to try and improve the experience of wiring up a set of Twirp RPC services via a function, along the lines of:

```go
func Register(mux http.ServeMux, twirpServices ... twirp.TwirpServer) {
	for _, service := range twirpServices {
		mux.Handle(service.Prefix(), service)
	}
}
```

I had based this on the [docs](https://twitchtv.github.io/twirp/docs/mux.html) about adding services to an existing `http.ServeMux`, but ran into the following nuances of how `TwirpServer` and `const *Prefix` are currently implemented:

* When you call `New` on a generated service you get a `TwirpServer`. This is good thing, however the interface definition is **inside** the generated code and its package. This means that you can't refer to the interface in more general context. There doesn't seem to be anything implementation specific about this interface that would lead to it needing to be part of the generated code, so I am wondering if it couldn't be moved up into the `twirp` package.
* Having a `const` with the path prefix created as part of code generation is super useful, but it can be hard to get to. Given that the description of `TwirpServer` is "TwirpServer is the interface generated server structs will support: they're HTTP handlers with additional methods for accessing metadata about the service," I wonder if it wouldn't make sense to add a `Prefix()` method to the interface and then generate an implementation that returns the `const` value. The prefixs would then be accessible in a more generic way.

I think these changes are generally beneficial in addition to enabling the example that I started with. However I am fairly new to this code base, so if there are reasons that it is this way or other things that I am missing, please let me know. I am also happy to create a PR that implements this if it is deemed to be a good path forward.

**Comment by gorzell** [comment]
I think most of the first point is answered in: https://github.com/twitchtv/twirp/issues/96

**Comment by dpolansky** [comment]
Thanks for the proposal. I agree that the comment by @spenczar in #96 does a great job describing the problems Twirp would run into if we moved the `TwirpServer` interface out of the generated code. I agree with your point about the path prefix being hard to get to in a generic way, and adding that to the generated code seems fairly painless. I'm going to shop this by the other maintainers this week and see what they think.

**Comment by spenczar** [comment]
Right, you can define an interface type that covers your needs, and not need to reference the generated one, since interfaces that are identical are mutually assignable.

The second concern, on prefixes, is more interesting to me. I agree that it is painful to get generic access to prefixes today, but would like to understand why this would be useful. Could you give an example?

**Comment by gorzell** [comment]
@spenczar I think the best example I have right now is the one I gave above, being able to write helper methods that can configure things like `http.ServeMux` en mass for a set/list of twirp services.  i.e. we have a general health check service that we want to run next to our "business logic" service.

**Comment by spenczar** [comment]
Okay, let me make sure I understand this use case. Today, to register some standard services like a health checker and a metrics exporter, you'd do something like this:
```go
func RegisterStandardServices(mux *http.ServeMux) {
  mux.Handle(health.HealthCheckPathPrefix, health.NewHealthCheck(...))
  mux.Handle(metrics.MetricsExportPathPrefix, metrics.NewMetricsExport(...))
}
```
And users use it like this:
```go
mux := http.NewServeMux()
standards.RegisterStandardServices(mux)
mux.Handle(bizlogic.BizLogicPathPrefix, newBizLogic())
```

---
In contrast, you'd like a helper that looks like this:
```go
func Register(mux *http.ServeMux, servers ...TwirpServer) {
  for _, s := range servers {
    mux.Handle(s.Prefix(), s)
  }
}
```
So your users could do:
```go
mux := http.NewServeMux()
Register(mux, health.NewHealthChecker(), metrics.NewMetricsExporter(), newBizLogic())
```

Do I have that about right? The proposed new version doesn't seem obviously better to me, merely different, but I could be missing something here.

**Comment by gorzell** [comment]
@spenczar I think that you have represented the use case correctly.  I agree that the difference is subtle, but I think there is one.  My example can be put into a library that has no knowledge of the implementations that might be involved, and as a result doesn't bring in any extra dependencies.  Maybe that isn't appealing enough to be worth it? It seems like given that fact that every `TwirpServer` has to have a `PathPrefex`, there isn't a ton of harm in exposing that in a way that doesn't require knowing the exact type and `const` name you are dealing with?  It could also be that I am trying to apply patterns from other languages that just don't make sense in Go.

**Comment by spenczar** [comment]
Oh, I agree there isn't a ton of apparent harm, but every expansion of an interface is hard to walk back from, so I'm just generally very conservative. This does seem quite innocuous, I agree - but we should still design carefully, and know exactly what we're getting when we add a new feature like this.

What sort of library would want to be able to iterate over servers and get their prefixes, but _not_ bring in extra dependencies? The "turn on a standard set of services" library made sense to me, but I am having trouble picturing a library that doesn't reference any other services. The `Register` helper I wrote above is so tiny and trivial, it doesn't seem to enough value to its own library just on its own.

**Comment by gorzell** [comment]
I am working on an internal library that has things we think are value add on top of the base twirp code.  This is mostly things like ServerHooks, client hooks, etc.  All of it is (and should be) agnostic to any generated code or business logic. This seemed like a reasonable place to also put some helper functions for things like registering services on a mux, etc.

In addition to this generic base library, we will also probably have a second even more opinionated library that actually composes things like default Hook chains and registers standard services.  That library with sit one level higher and have more expansive dependencies.  The pattern you proposed would fit better this this layer, and that may end up being the better choice.

The reason for the split is because we want to re-use any code that can be agnostic and give power users tools to compose their applications in customized ways if the opinionated composition isn't a good fit for them.

**Comment by spenczar** [comment]
I'm more and more sure that adding the prefix to the method set of `TwirpServer` is both harmless and possibly valuable. Let's go for it.

**Comment by gorzell** [comment]
I created #167 as a first pass implementation.

**Comment by gorzell** [comment]
Closing via #167
