### ISSUE TITLE
Define paths via options

### ISSUE THREAD

**Issue by thumbsized** [twitchtv/twirp#174]
Are there any plans to implement support for defining paths via options in the the proto definition - like grpc gateway does it?

It would essentially mean Twirp would provide a single server for grpc and what grpc gateway does and also support json - all at once.  Even swagger would then work with twirp(like it does with grpc gateway).

In current state, what Twirp produces is unusable for public consumption, in my case, but it has good potential.

**Comment by spenczar** [comment]
No, we have no plan to do this. Twirp's fixed route scheme makes it much easier to build generators in different languages, and makes it simple to cURL Twirp endpoints. I'm pretty happy with the fixed routing scheme.

Could you say more on why "what Twirp produces is unusable for public consumption?" Why does the public care about your paths?
