### ISSUE TITLE
Statsd-hooks - rate is always 1.0

### ISSUE THREAD

**Issue by manaspaldhe12** [twitchtv/twirp#175]
Currently, twirp sends metrics to StatsD at a rate of 1.0. Hence all requests lead to a metric being sent to StatsD.
Ref: https://github.com/twitchtv/twirp/blob/master/hooks/statsd/statsd.go

Since we host services that need to support 100k+ rps, this increases the load on the StatsD servers. It will be useful if we can customize the rate at which requests and successful responses are sent to StatsD. Errors should still be sent at a rate of 1.0.

Thank you.

**Comment by spenczar** [comment]
Yeah, this seems like something that should be configurable; the challenge would be doing so in a backwards-compatible way.

It seems like you'd want to set the sampling rate for different methods or different services separately; many services with low request rates _would_ want to record everything.

The simplest thing might be to write your own hooks implementation that meets your specific needs. Would that work?

**Comment by dpolansky** [comment]
I agree that writing a custom implementation of ServerHooks seems sufficient to address limitations of Twirp's statsd-hooks implementation. I am closing this for now.
