### ISSUE TITLE
Proposal: add context.SetHTTPCookie 

### ISSUE THREAD

**Issue by Bankq** [twitchtv/twirp#176]
Hi,

I'm trying to add 'Set-Cookie' header in Response but need some value computed inside RPC. 
Setting context value with a middleware doesn't seem to work since twirp doesn't allow rpc to modify context value (correct me if I'm wrong but only request hooks and middlewares can do that).

Wondering if anyone had a similar requirement and what would be the recommended solution.

Thank you!

**Comment by Bankq** [comment]
Omg I'm an idiot
https://godoc.org/github.com/twitchtv/twirp#SetHTTPResponseHeader

closing

**Comment by Bankq** [comment]
Hi, I'm reopening this issue with a modified feature request

`twirp.SetHTTPResponseHeader` invokes `http.Header.Set` which will overwrite exisiting header with the same key. 

I need to set multiple `Set-Cookie` headers. Having a `twirp.AddHTTPResponseHeader` which invokes `http.Header.Add` would be convenient.  If this sounds good I can help prepare a patch. 

Right now I'm bypassing this by injecting `ResponseWriter` (again) in request's context since twirp's one is internal. Additionally I'm wondering if the idea of exposing `ResponseWriter` directly had been brought up before. 

Thanks! Looking forward to the discussion.

**Comment by Bankq** [comment]
Hi,

After some thought I believe adding `AddHTTPResponseHeader` alongside with `SetHTTPResponseHeader` feels too generic. Sent a PR #177 to add `SetHTTPCookie` to directly  address the need since `Set-Cookie` is the only common use case I can think of.

Let me know what you think. Thanks!

**Comment by spenczar** [comment]
This seems unusual to me. I'm used to Twirp communicating through the request payload, rather than through headers. Can you say more about the use case of this?

**Comment by Bankq** [comment]
> This seems unusual to me. I'm used to Twirp communicating through the request payload, rather than through headers. Can you say more about the use case of this?

@spenczar sure!
The use cases for `Set-Cookie` headers, specifically for [CloudFront signed cookies](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-cookies.html) which requires 3 `Set-Cookie` headers. Currently twirp's `SetHTTPResponseHeader` API will overwrite if provides the header with the same key.

**Comment by spenczar** [comment]
Thanks. What sort of RPC are you doing where Twirp is the right definition language, but you care about CloudFront's signed cookies?

My gut is that this is something that's hard to represent via Twirp, but maybe that difficulty is correct. Twirp is best when you control both client and server, and can fully describe the request/response payloads with protobuf. I'm a little concerned that cookies are a way to pass state that's pretty distant from the protobuf definition of the RPC. Are you able to say more about the details here - why a Twirp RPC is the best way to set a CloudFront signed cookie?

The risk here is that when we add more ways to pass state, it's easier for engineers to make mistakes and choose the wrong tool for the job.

**Comment by Bankq** [comment]
@spenczar yeah I realized more details are helpful here.

The use case is around video playback. I control both client and server. The rpc is to fetch playback information given an asset. Response looks like
```
{
  "manifest_url": "http://cloud-front.com/foo/bar.m3u8"
}
```
An m3u8 is a manifest file contains relative links to actual media fragments which also resides on CDN.

To protect access to the objects on cdn, server generates a signature token can be either carried as query string  in the URL, or set as cookie. It would be a non-issue for the manifest itself but to use query string for all the fragments described in manifest, we'll have to edit it on the fly. I'm hoping to utilize set-cookie so that manifest and fragments can share the same token and all clients can share the same CDN object.

To your concern on choose the wrong tool for the job, I understand. This is basically why I was initially proposing having a `AddHTTPResponseHeader` along side with `SetHTTPResponseHeader` to make multiple headers with same key possible. Having a `SetHTTPCookie` API does sound a bit out of the place.

**Comment by spenczar** [comment]
@Bankq Could the server's response type be this?

```
{
  "manifest_url": "http://cloud-front.com/foo/bar.m3u8",
  "signature_token": "xxxxxxxxxxx"
}
```

Then the client decides to set a `Cookie` header or use a query string when it requests the M3U8 or the fragments. It has the right data to do that. It also makes more sense than using `Set-Cookie`; unless your server is under the `cloud-front.com` domain, it's not permitted to `Set-Cookie` for `cloud-front.com` - cross-domain cookie setting would be a big security hole.

If you separate things in this way (where the client has to pull out the signature token and decide how to use it when requesting from cloudfront), the Twirp communication between client and server is pure Twirp; it doesn't have a dependency on how CloudFront implements auth.

**Comment by Bankq** [comment]
@spenczar 
Yes they are on the same domain. I used `cloud-front.com` as an example.

Puting token in response is what I meant "manifest will be a non-issue". The difficult part is re-using the token for all the underlying fragments that are linked in the manifest file. Client feeds the manifest url to the player which operates as a black box. I can perhaps intercept all the outgoing network calls and append the token there but as you can see cookies is perfect for this use case (which is also why cloudfront supports it I believe). 

Is there a particular reason Twrip doesn't support response headers with same key?

**Comment by spenczar** [comment]
>  Client feeds the manifest url to the player which operates as a black box.

Ok, now I've got it! In my mind, this means you don't really control the client, since it sounds like it's operating within a browser or something with a media engine.

>  can perhaps intercept all the outgoing network calls and append the token there but as you can see cookies is perfect for this use case (which is also why cloudfront supports it I believe).

This seems terrible, yes, but it also doesn't seem necessary. Why can't the client logic be to set its own cookies before passing the manifest into the player?
```
get {"manifest_url": "...", "signature_token": "..."} response from server
set cookies (eg via javascript's 'setCookie')
pass manifest to player
````

> Is there a particular reason Twrip doesn't support response headers with same key?

Nothing technical. I just like to ask a lot of questions to really understand before adding to Twirp's API area. It has worked well for us in the past. The small size of Twirp's API is a big benefit.

**Comment by Bankq** [comment]
@spenczar thanks!

> > Client feeds the manifest url to the player which operates as a black box.
> 
> Ok, now I've got it! In my mind, this means you don't really control the client, since it sounds like it's operating within a browser or something with a media engine.
> 
Hah one could say that yes!

> > can perhaps intercept all the outgoing network calls and append the token there but as you can see cookies is perfect for this use case (which is also why cloudfront supports it I believe).
> 
> This seems terrible, yes, but it also doesn't seem necessary. Why can't the client logic be to set its own cookies before passing the manifest into the player?
> 
Yeah that's one of the options the team and I discussed about. We are trying to simplify the client logic. If using `Set-Cookie` header, client works out of the box.

> ```
> get {"manifest_url": "...", "signature_token": "..."} response from server
> set cookies (eg via javascript's 'setCookie')
> pass manifest to player
> ```
> 
> > Is there a particular reason Twrip doesn't support response headers with same key?
> 
> Nothing technical. I just like to ask a lot of questions to really understand before adding to Twirp's API area. It has worked well for us in the past. The small size of Twirp's API is a big benefit.

I understand. Simplicity is the big reason we adopt twirp at the beginning.

`AddHTTPResponseHeader`  feels more "twirp-y" but definitely looks verbose side by side by `SetHTTPResponseHeader`. `SetHTTPCookie` addresses the most common use case of same key headers but feels not "twirp-y".

Right now I'm injecting `ResponseWriter` using a middleware to bypass this. Wondering if supporting same key response header is something Twirp plans to support.

**Comment by spenczar** [comment]
I think that, all things considered, this isn't something we should add to Twirp, at least not yet. Your workaround through middleware is appropriate; it's not a common-enough problem to justify inclusion in Twirp's API.

If more people encounter this, please - chime in on this issue, and we can revisit it.

For posterity, here's how I picture the middleware working. It's not very onerous:

```go
package twirpcookies

import (
	"context"
	"errors"
	"net/http"
)

// WithCookies configures an http.Handler (like any Twirp server) to enable
// setting cookies with the SetCookie function.
func WithCookies(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		ctx = context.WithValue(ctx, rwkey, w)
		r = r.WithContext(ctx)
		h.ServeHTTP(w, r)
	})
}

// SetCookie sets an http Cookie for a response being handled in the given
// context. It returns an error if and only if the context has not been
// configured through the WithCookies function.
func SetCookie(ctx context.Context, cookie *http.Cookie) error {
	w, ok := ctx.Value(rwkey).(http.ResponseWriter)
	if !ok {
		return errors.New("unable to get ResponseWriter from context, middleware might not be set up correctly")
	}
	http.SetCookie(w, cookie)
	return nil
}

type ctxkey string

const rwkey ctxkey = "responsewriter"
```

**Comment by Bankq** [comment]
@spenczar This actually looks scarily similar to my code :) 

Thanks for the discussion!
