### ISSUE TITLE
Add WriteError to the twirp package

### ISSUE THREAD

**Issue by mfridman** [twitchtv/twirp#186]
`WriteError` is great for standardizing twirp errors.

Proposal is to add `WriteError`-like functionality to `twitchtv/twirp` so we can get structured errors in http middlewares outside twirp services. 

> users would be able to access WriteError without importing an rpc service. Especially since twitchtv/twirp is probably already being imported to construct an error

1. add a `WriteError`-like implementation to `twitchtv/twirp` itself

2. add a method (not backwards-compatible) to `Error` interface that's "opposite" of `Msg() string`, i.e., returns a _non_ human-readable, structured messages describing the error.

Thoughts?

---

We now have multiple twirp services mounted to our router, but a single middleware stack for these specific services. So which `<service>.WriteError` would we use? It probably doesn't matter and creates an unnecessary import.

**Comment by mfridman** [comment]
The above 2 proposals aim to achieve the same thing, i.e, being able to compose and return a structured JSON error in the flavor of Twirp errors that is twirp service-agnostic.

The idea for 2 was, if one composed a `twirp.Error` then we want to return a "structured" JSON object instead of a "human-readable" message. It's a lower-level abstraction that would be useful for those who want to create custom wrappers such as `foo.Respond(w, r, err.JSON())`.

Problem is the current `twirp.Error` interface doesn't expose (maybe I'm missing something obvious though) a way to retrieve a JSON-structured error in the same manner as an rpc service. 

Error() returns `"twirp error <Type>: <Msg>"`

and Msg() returns an unstructured (human-readable) error

But let's scratch 2. I think majority of the time proposal 1 will used within the scope of a response writer anyways; where we simply want to return a structured error to the client. And `twirp.WriteError` would accomplish this nicely.

Would you be interested in a PR that brings a generic `WriteError` to the `twitchtv/twirp` pkg?

I can't see any immediate drawbacks, thoughts welcome.

**Comment by mfridman** [comment]
Just realized this is a duplicate of #161 (and maybe others). 

lmk if you're interested in this and I'll submit a PR, or if you had further thoughts/reservations.

**Comment by mfridman** [comment]
ping @spenczar, would you consider a PR for adding `WriteError` to the std pkg ?

**Comment by spenczar** [comment]
@mfridman Yep, I'd be in support of that.
