### ISSUE TITLE
Use ServerHooks to validate request message content

### ISSUE THREAD

**Issue by manhdaovan** [twitchtv/twirp#188]
If the [`RequestReceived` of `ServerHooks`](https://github.com/twitchtv/twirp/blob/master/hooks.go#L38) struct is changed to `func(ctx context.Context, req interface{}) (context.Context, error)` instead of `func(context.Context) (context.Context, error)`, [go-proto-validators](https://github.com/mwitkow/go-proto-validators) can be integrated to validate request message content.

For example:

```go
type Validator interface{
    Validate() error
}
func ValidateReq(ctx context.Context, req interface{}) (context.Context, error){
    if r, ok := req.(Validator); ok {
		if err := r.Validate(); err != nil {
			return nil, err
		}
	}
	
	// other logic
}
```

**Comment by spenczar** [comment]
This has come up a few times, and after some thorough discussion, we've decided not to do it. Previous issues have the discussion: 
https://github.com/twitchtv/twirp/issues/187
https://github.com/twitchtv/twirp/issues/184
