### ISSUE TITLE
Return error from twirp.WriteError

### ISSUE THREAD

**Issue by ofpiyush** [twitchtv/twirp#201]
Moving discussion from the [PR](https://github.com/twitchtv/twirp/pull/192#discussion_r344446180) as @spenczar requested.

**Recap:**

Current implementation of `twirp.WriteError` does not return any error occurred while writing the TwirpError.

<details><summary>Humor</summary><p><em>WriteError does not return the error if an error occurs while writing the error.</em></p></details>

Since the public API currently returns nothing, all existing code looks like

```go
twirp.WriteError(resp, err)
```

As no return is being processed, adding a return to this method will not break existing code.

**Comment by spenczar** [comment]
You're right that it won't break most code. The only exception would be that the function's type changes, so if someone has a `var w func(*http.ResponseWriter, error) = twirp.WriteError`, that code will break. That seems pretty unusual, and the function is new enough that it might be safe to modify without any significant changes.

It's a bit of a violation of semver to make this part of a minor release, but I think it might be a forgivable one.

**Comment by spenczar** [comment]
Oh, and in case it isn't obvious - yes, it should return an error if it fails to write.
