### ISSUE TITLE
Expose stringutils package for custom plugins

### ISSUE THREAD

**Issue by mickeyreiss** [twitchtv/twirp#203]
We have a bug where an abbreviation in a method name was rendered in an unexpected way, and we have a custom twirp protoc plugin (for Swift/iOS) that made a different assumption about casing rules.

FWIW - Our plugin uses https://github.com/iancoleman/strcase for casing.

The rpc in question is `rpc DoSomethingWithW4s (DoSomethingWithW4sRequest) returns (DoSomethingWithW4sResponse)`. (_W4_, as in the tax form pluralized). Twirp generates `DoSomethingWithW4S`, but our plugin generated `DoSomethingWithW4s`—this applied to both the function names as well as the HTTP paths (this was the breakage).

Could you expose the https://github.com/twitchtv/twirp/tree/master/internal/gen package so that custom plugins written in Go can utilize the library? Is there already a way to do this, so that custom plugins can follow twirp's casing rules precisely.

**Comment by WIZARDISHUNGRY** [comment]
I'm using https://github.com/twitchtv/protogen

**Comment by spenczar** [comment]
Right, the github.com/twitchtv/protogen/stringutils package should be providing this already.
