### ISSUE TITLE
unsupport Content-Type: application/x-www-form-urlencoded ? 

### ISSUE THREAD

**Issue by leeyongda** [twitchtv/twirp#204]
### only support json with http post ?

**Comment by leeyongda** [comment]
## only support json with http post ?

**Comment by spenczar** [comment]
I'm sorry, I don't understand the question. I think you're asking about an error you saw when hand-writing a request. Twirp only supports POST, and the `Content-Type` header must be either `application/protobuf` or `application/json` (https://twitchtv.github.io/twirp/docs/spec_v5.html#requests)
