### ISSUE TITLE
Suggestion: Returning a non nil context

### ISSUE THREAD

**Issue by simar7** [twitchtv/twirp#206]
Hello,

First of all thanks for making twirp open source. I'd like to make a suggestion that I noticed while working with it.

Currently the `WithHTTPRequestsHeaders` returns a `nil` context back in case of the caller setting a reserved header field. Relevant code: https://github.com/twitchtv/twirp/blob/master/context.go#L70-L78

This introduces the possibility where existing callers may try to use the returned `nil` context without first checking the returned error. Possible use case could include downstream context cancelation in such a scenario by doing something like `context.WithCancel(ctx)` where `ctx` is the returned context from `WithHTTPRequestHeaders` which will be `nil` in this case. Such scenarios could result in a panic.

I'd like to make a suggestion to resend back a non nil context in these erroneous cases. It could just be sending back the same context that was passed in, along with an non nil error just like it is today.

So something like:
```
	if _, ok := h["Accept"]; ok {
		return ctx, errors.New("provided header cannot set Accept")
	}
	if _, ok := h["Content-Type"]; ok {
		return ctx, errors.New("provided header cannot set Content-Type")
	}
	if _, ok := h["Twirp-Version"]; ok {
		return ctx, errors.New("provided header cannot set Twirp-Version")
	}
```

Where `ctx` is the passed in context from the caller.

Thoughts? I can try to work on a PR if you think this is something that makes sense.

**Comment by spenczar** [comment]
I understand this, but I think I prefer the code as-is. It's pretty idiomatically expected in Go to check errors before using returned values from functions. The code you're describing would have to be something like
```
var (
  err error
  ctx = context.Background()
)

ctx, err = twirp.WithHTTPRequestHeaders(ctx, header)
ctx, cancel := context.WithCancel(ctx)
if err != nil {
  handle(err)
}
```

To my eyes, that just looks flatly incorrect. Errors ought to be checked first.
