### ISSUE TITLE
Generated Client For Dart

### ISSUE THREAD

**Issue by ansarizafar** [twitchtv/twirp#209]
Google's Flutter framework is becoming very popular and an official generated Dart client will greatly help Flutter/Dart developers to build cross platform apps with Twirp. 

Dart client mentioned in the read me is not maintained anymore. I request you to please consider this proposal as a priority.

**Comment by spenczar** [comment]
I have zero expertise in Dart, sorry, but I agree there is room for a good client implementation. You could be the one to make a good client generator, and I'd encourage you to try. Twirp is simple enough that, if you know the target language well, you can usually write a client generator in a few hours. I'd be happy to help you through the process, if you like.

**Comment by dpolansky** [comment]
As @spenczar mentioned, please let us know if we can be helpful if you decide to build a Dart client. I am closing this issue for now.
