### ISSUE TITLE
Support empty JSON requests

### ISSUE THREAD

**Issue by leighmcculloch** [twitchtv/twirp#21]
## What I did
I created a service method that takes no inputs. It has a request message type, but that type has no fields.

```
service Geo {                               
  rpc Get(GetRequest) returns (GetResponse);
}                                           
                                            
message GetRequest {                        
}                                           
                                            
message GetResponse {                       
  string country = 1;                       
}                                           
```

I made a request to the server with content-type `application/json` and an empty body.

```
curl \
  --request POST \
  --header "Content-Type: application/json" \
  http://localhost:8080/twirp/app.Geo/Get
```

## What happened

The server responded with an error.

```json
{"code":"internal","msg":"failed to parse request json: EOF","meta":{"cause":"*app.wrappedError"}}
```

## What I thought would happen

I thought the server would response with the result of the method.

```json
{"country":"US"}
```

## What I needed to do to make it work

I added an empty json object as the body of the request.

```
curl \
  --request POST \
  --header "Content-Type: application/json" \
  --data '{}' \
  http://localhost:8080/twirp/app.Geo/Get
```

## Proposal

Support empty request body on requests with content-type `application/json`.

**Comment by spenczar** [comment]
Could you talk more about why you'd want this?

Doing this would mean we are no longer compatible with the jsonpb serialization. It would mean Twirp has its own special serialization rules. I think we only want to deviate if we have a very, very good reason to do so - I'd rather not maintain a fork of the protobuf spec.

**Comment by leighmcculloch** [comment]
👍 Makes sense. I think I was thinking of convenience when querying services that have no inputs, but agree we shouldn't diverge from standards and an empty string is invalid JSON, which makes no sense when sending the content-type as json.
