### ISSUE TITLE
Return unmarshal errors for malformed requests

### ISSUE THREAD

**Issue by mfridman** [twitchtv/twirp#214]
A recent change has been causing a bit of grief for our team. Hoping to start a discussion on bringing back prior functionality.

Specifically, prior to #182, a client would get back an error message containing the _raw_ unmarshalling error.

We found these errors to be _very_ useful, especially during development.

https://github.com/twitchtv/twirp/pull/182/files#diff-a3a2b0741a88a528d33eb1f40bef6b04L1078

So, the suggestion is to return unmarshalling errors for malformed requests.

**Comment by spenczar** [comment]
That change did two things. First, it added a new error code; second, it obfuscated the marshaling error text.

Reverting the new error code is hard, and also not really helpful to you, I think.

Adding the full unmarshal error text back into the transmitted error messages seems straightforward. Our argument at the time was a vague "security" concern, which I think is kind of bogus on more reflection.

I'd be in favor of adding more detail to those error messages, yes.

**Comment by mfridman** [comment]
> Reverting the new error code is hard, and also not really helpful to you, I think.

Correct. No issues with the error code  portion of that PR.

I suggest we propagate the error from the Unmarshaler in a similar mechanism as before:

pseudo:  `"failed to parse request json: " + err`

I'll let this sit for a bit, see if someone picks it up. Otherwise I'll submit a PR and we can chat some more?

**Comment by spenczar** [comment]
That looks like a good enough error message to me, yep.

**Comment by marioizquierdo** [comment]
@mfridman a PR would be appreciated 😄
