### ISSUE TITLE
"No handler for path" should be logged server side

### ISSUE THREAD

**Issue by SauronKitty** [twitchtv/twirp#218]
As part of the `ServeHTTP` function generated by Twirp, the default case which handles paths that have no corresponding handlers will only return an unlogged response message to the client. This makes it difficult to have metrics around these calls.

**Comment by dpolansky** [comment]
The `ServeHTTP` method for a generated Go Twirp server calls `writeError` with the `twirp.BadRoute` error code when the server receives an unexpected HTTP method or URL path. The `writeError` function will call the `Error` server hook if it is set, which would allow for instrumentation around that specific error code. Does the `Error` server hook address your use case sufficiently?

**Comment by SauronKitty** [comment]
Yes it does. Thank you. I overlooked the `serverHooks`.
This can be closed.
