### ISSUE TITLE
Add curl example using protobuf format to wiki

### ISSUE THREAD

**Issue by leighmcculloch** [twitchtv/twirp#22]
The wiki has an example of how to curl using the json format here:
https://github.com/twitchtv/twirp/wiki/HTTP-Routing-and-Serialization#making-requests-on-the-command-line-with-curl

It would be useful I think if this section also contained an example of how to curl using protobuf, which is possible if the user has `protoc` installed, which is likely since it's required for building the autogenerated code.

e.g.
```
echo "inches:10" \
	| protoc --proto_path=$GOPATH/src --encode twirp.example.haberdasher.Size ./rpc/haberdasher/service.proto \
	| curl -s --request POST --header "Content-Type: application/protobuf" --data-binary @- http://localhost:8080/twirp/twirp.example.haberdasher.Haberdasher/MakeHat \
	| protoc --proto_path=$GOPATH/src --decode twirp.example.haberdasher.Hat ./rpc/haberdasher/service.proto
```

I'd open a PR to add it to docs, but I don't see a way of doing that since the docs are in the github wiki and not in the repo.

**Comment by spenczar** [comment]
Wow, this is pretty cool. I think this is worth putting _somewhere_, but I'm not totally sure where just yet.

Let's wait until we have some better-structured docs, which should come via #1 - I'd like to move off the wiki, it's hard for people to contribute to.

**Comment by leighmcculloch** [comment]
#1 is closed now, where's the right place to open a PR for this change?

**Comment by spenczar** [comment]
Right, sorry about that. I've got a new pass at docs, #75, which I plan to merge today, hold tight.

**Comment by spenczar** [comment]
Yeah, it's still worth adding this somewhere - it's just such a good trick.
