### ISSUE TITLE
README alludes to the ability to generate python servers, but this doesn't seem to be the case

### ISSUE THREAD

**Issue by iandelahorne** [twitchtv/twirp#220]
We're evaluating various RPC frameworks here at Patreon, and I suggested we look into Twirp since it seemed to have the ability to generate Python servers (we're a Python shop).

Specifically, the line (in README.md) `This repo only has the official generators, which write out Go and Python code`, while not specifically stating that Python servers are generated, also doesn't completely rule it out.

To prevent disambiguity, this might be something you want to add to the table, as well as reformatting to `This repo only has the official generators for Go (client & server) and Python (client)`

**Comment by ofpiyush** [comment]
Pasting my comment from the slack channel.
------
We have an internal python server implementation that we use on a couple of services. We can clean it up and open source/contribute.

Current opinions up for debate:
- Server is an asgi server (abstracted so wsgi should be possible without a lot of work)
- We have a context object that we use similar to go. (There's no context cancelling on it yet)
- The context object forces use of a logger, defaults to structlog.

**Comment by vincentng-z** [comment]
@ofpiyush - any rough estimates on the timeline to clean up and eventually release?

**Comment by ofpiyush** [comment]
Didn't realise there was pull for it!

I'll ping folks in the company on Monday and post an update as soon as I find a taker.

**Comment by ofpiyush** [comment]
We figured that none of the python servers are open to public internet and there's no sensitive information in the repo so here's the link to our current version. 

We'll remove verloop specific things and bad practices from here and make proper releases.

https://github.com/verloop/vtwirp/tree/vcontext

@spenczar what is the eventual goal here? Should we work towards merging this into the main repo some day?

**Comment by dpolansky** [comment]
@ofpiyush please feel free to submit a PR adding a link to vtwirp when you are ready. I think it makes the most sense for new clients and servers to exist in their own repositories to establish clear ownership.

**Comment by ofpiyush** [comment]
@dpolansky we can close this now as the readme has also changed.
