### ISSUE TITLE
Tiny documentation hiccup?

### ISSUE THREAD

**Issue by anvk** [twitchtv/twirp#223]
Hi I'm pretty new to gRPC and want to say that this library is amazing. Want to use it for one of my projects. However, I noticed that in the `Best Practices` doc you recommend the following structure:

```
/cmd
    /<service>
        main.go
/rpc
    /<service>
        service.proto
        // and auto-generated files
/internal
    /<service>server
        server.go
        // and usually one other file per method
```

with the following example:

```
/cmd
    /haberdasherserver
        main.go
/rpc
    /haberdasher
        service.proto
        service.pb.go
        service.twirp.go
/internal
    /haberdasherserver
        server_test.go
        server.go
        make_hat_test.go
        make_hat.go
```

I believe it should be the following if you use your best practices suggestions.

```
/cmd
    /haberdasher
        main.go
```

OR

```
/cmd
    /<service>server
        main.go
```

What is the best practice here?

**Comment by mfridman** [comment]
In most Go applications (not just Twirp) the `main.go` file will live under `./cmd/some_name/main.go`

if you do a plain `go build .` the resulting binary will have the name of the directory, e.g., `some_name` or `haberdasher` or `haberdasherserver`

So you probably name it whatever makes sense in your context.
