### ISSUE TITLE
undefined: *.twirp.go 

### ISSUE THREAD

**Issue by nhurwitz** [twitchtv/twirp#236]
(this might be related to https://github.com/twitchtv/twirp/issues/169)

I'm running `go 1.13` using go mod. I see in my go vendor and go src the compiled *.twirp.go and `*.pb.go` files in the same package. However, when I try to build my source code, I'm able to use `*.pb.go` but not `*.twirp.go` even though they're colocated and should be available through the same import statement.

**Comment by nhurwitz** [comment]
to elaborate, this will run

```
package main

import (
	"fmt"
	"github.com/foo-organization/schema/go/bar"
)

func main() {
	fmt.Println(bar.GetBarRequest{})
}
```

but this will result in `./main.go:10:14: undefined: upload.BarPathPrefix`
```
package main

import (
	"fmt"
	"github.com/foo-organization/schema/go/bar"
)

func main() {
	fmt.Println(bar.BarPathPrefix)
}
```

I can see the compiled `bar.twirp.go` both in the vendor/ folder and in my $GOPATH/src

**Comment by dpolansky** [comment]
Could you possibly make a tiny github repository with the setup you describe as a reproducer for this issue?

**Comment by nhurwitz** [comment]
I'll try to get to it this weekend

**Comment by dpolansky** [comment]
Closing this for now. Please leave a comment if you would like to revisit this.
