### ISSUE TITLE
Support for custom HTTP transcoding

### ISSUE THREAD

**Issue by amitmahbubani** [twitchtv/twirp#238]
Would Twirp consider supporting custom HTTP transcoding via Google's [HttpRule](https://cloud.google.com/endpoints/docs/grpc-service-config/reference/rpc/google.api#google.api.HttpRule) in protobuf?

Reason: We use Twirp internally for microservices, but some of these services need to expose custom, strictly REST, interfaces for external customers. 

For example, REST endpoints like:
```sh
POST /users
GET /users/:id
GET /users
```

to map to Proto:
```protobuf
service Users {
    rpc Create(..) returns (..);
    rpc Get(..) returns (..);
    rpc List(..) returns (..);
}
```

**Comment by dpolansky** [comment]
As discussed in #239, Twirp will likely not support mechanisms for this, but folks at Twitch have written code to translate REST-style HTTP requests to Twirp requests, and Twirp responses back to REST-style HTTP responses. The complexity of presenting a Twirp service for consumption over REST-style HTTP seems best implemented as a standalone package or tool.
