### ISSUE TITLE
Wiki example content issues

### ISSUE THREAD

**Issue by andyleap** [twitchtv/twirp#24]
There are several code issues on the https://github.com/twitchtv/twirp/wiki page.  While nothing is advertising those snippets as 100% perfect, it'd be nice to have the egregious errors fixed.  Notably: 

## Server snippet:

```
func (s *HelloWorldServer) Hello(ctx context.Context, req *pb.HelloReq) (hat *pb.HelloResp, error) {
```
the return values mix named and unnamed returns, which is unallowed.  Consider removing the "hat" name.

## Client snippet

The client created is targeting port 8000, where the server was put on port 8080. 

The client is also doing reversed logic err check:
```
if err != nil {
    fmt.Println(resp.Text) // prints "Hello World"
}
```
which should only print anything if an error was returned, which is almost assuredly the wrong thing to be doing here.  

In addition, I'd consider changing `resp, err = client.Hello(` to `resp, err := client.Hello(`, as there's nothing in this snippet creating resp or err, so it would seem cleaner this way

**Comment by spenczar** [comment]
Thanks for pointing these (indeed egregious) errors out. I've now put in code that I've verified actually compiles.

**Comment by andyleap** [comment]
It does now compile, but it still does not work, as the client and the server are using different ports, and you only print the response if the rpc returns an error....

**Comment by spenczar** [comment]
Sheesh! This will be a lot better to keep up with when we have docs in a place that can get contributions from the outside world. Sorry for the runaround, but thank you for being diligent.
