### ISSUE TITLE
C++ Client Support

### ISSUE THREAD

**Issue by brendanstennett** [twitchtv/twirp#242]
What would be the recommended path for supporting C++ client code? I don't see any mention of C++ in the docs and was wondering if anyone had suggestions on how to get started down this road?

**Comment by marioizquierdo** [comment]
Other client implementations should be done on their own repos. You can see some examples in https://github.com/twitchtv/twirp#implementations-in-other-languages

If the new client or service gets some adoption, we could link to that project in the README here.

**Comment by brendanstennett** [comment]
Ok! Will keep that in mind. 

Thank you.
