### ISSUE TITLE
Question: Docker Image

### ISSUE THREAD

**Issue by damianoneill** [twitchtv/twirp#248]
Hi Guys, quick question, is there a versioned Docker image available for twirp with all its dependencies?  I had a look on hub, but only found a couple of older images. 

Thanks,
Damian.

**Comment by dpolansky** [comment]
There are no official Docker images for the generators in this repo. I don't think one will be provided because I don't think it makes sense for Twirp to be responsible for including dependencies like `protoc` or `protoc-gen-go` in an image.

**Comment by damianoneill** [comment]
@dpolansky and others that are interested.  Here is a target for the current makefile that will build a docker image with the deps. 

__NOTE__ only tested on OSX

Checkout the repo, switch branch to whatever version you're interested in and add this target to the Makefile. 

```makefile
DOCKER_RELEASE_NAME ?= github.com/twitchtv/twirp
DOCKER_RELEASE_VERSION ?= $(shell git describe --tags --abbrev=0)
define DOCKERFILE_BODY
FROM $(DOCKER_RELEASE_IMAGE)
WORKDIR /twirp
RUN apt-get -y update && apt-get --no-install-recommends -y install unzip && rm -rf /var/lib/apt/lists/*
COPY install_proto.bash /app/
COPY release/protoc-gen-twirp-Linux-x86_64 /go/bin/protoc-gen-twirp
RUN /app/install_proto.bash
RUN go get github.com/golang/protobuf/protoc-gen-go # not versioned
ENTRYPOINT ["/usr/local/bin/protoc"]
endef
export DOCKERFILE_BODY
docker_gen: # release_gen
ifeq (,$(wildcard release/protoc-gen-twirp-Linux-x86_64))
	$(error release not found, run make release_gen)
endif
	@echo "$$DOCKERFILE_BODY" > DOCKERFILE
	docker build -t $(DOCKER_RELEASE_NAME):$(DOCKER_RELEASE_VERSION) -f DOCKERFILE .
```

Run 

```console
make docker_gen 
```

This will create an image with the current git tag (ignores dirty value). 

```console
$ docker images | grep twitchtv/twirp
github.com/twitchtv/twirp                                                   v5.12.0                  23dc71d916d2        4 minutes ago       836MB
```

The built image is huge, as its parent is go, since building locally I'm not concerned about this.  If publishing the Dockerfile, you should consider migrating the generated DOCKERFILE to a multistage build. 

It can be executed as follows:

```console
docker run -v "$(pwd):/twirp" github.com/twitchtv/twirp:v5.12.0 --proto_path=/go/src:. --twirp_out=. --go_out=. ./example/service.proto
```
