### ISSUE TITLE
Server handler: Context and http.Request

### ISSUE THREAD

**Issue by titpetric** [twitchtv/twirp#252]
I see in generated code ServeHTTP code that the context is being extended, and then passed into individual RPC functions with the `func serveName(ctx, http.ResponseWriter, *http.Request)` for each RPC and `writeError` respectively.

- [http.Request{}.WithContext](https://golang.org/pkg/net/http/#Request.WithContext) could create a shallow copy+bind r.Context(),
- I'm assuming that a http.Mux could be used in ServeHTTP directly referencing the RPC functions, like so:

~~~go
mux := http.NewServeMux()
mux.HandleFunc("/twirp/user.UserService/Get", s.serveGet)
mux.HandleFunc("/twirp/user.UserService/GetMulti", s.serveGetMulti)
mux.HandleFunc("/twirp/user.UserService/Search", s.serveSearch)
...
mux.ServeHTTP(w, r)
~~~

..., appropriately created outside of ServeHTTP so it can be reused to be nice to the GC.

**Comment by spenczar** [comment]
The current implementation uses `http.Request.Context()`: https://github.com/twitchtv/twirp/blob/master/example/service.twirp.go#L177. I'm not sure I understand what you're saying, could you say more about what's insufficient?

It's probably true that `http.Mux` could be used instead of `switch req.URL.Path`, but it's not clear to me why that would be better, just different. The current code is very simple and clear, I think. It's pretty easy to see that it's correct.

**Comment by titpetric** [comment]
L117 creates an independent context which is then passed to (ctx, writer, req). Creating a request copy would leave all .serve* functions as http.Handlers, and context in them could be gotten with r.Context();

With it, the handlers could also be reused for non-Twirp requests, e.g. declaring a few GET/POST/DELETE REST-like interfaces.

**Comment by spenczar** [comment]
I guess I don't understand why that's preferable. Each of those is an unexported method; the current layout is an implementation detail for making a valid Twirp server in Go. How would a change here make Twirp better, or any different?

**Comment by marioizquierdo** [comment]
@titpetric are you suggesting an idea to make the Twirp implementation more modular? Is this just a refactor for the internal code, or do you see a compeling use-case for making the methods exported so they can be used as independent `http.HandlerFunc` on their own? for example:

```go
mux := http.NewServeMux()
mux.HandleFunc("/myownroute/foobar.UserService/Get", s.ServeGetJSON) // << assuming ServeGetJSON is exported
```

In general, Twirp implementation should be unexported, the smaller the API surface the easier it is to maintain it in the future. But maybe you have a compelling use case for this?

**Comment by titpetric** [comment]
@marioizquierdo You are correct, there is an use case, even for the unexported functions to be a http.Handler. I'm splitting some RPCs currently into separate services based on intended clients, but it often makes sense to split the same problem domain into RPC calls that are meant for the browser (so, public), and some that are meant for the infrastructure (healthchecks, etc.). Having a compatible http handler would allow me wrapping them on a mux in the same package.

Particularly, I already have code like this:

~~~go
func NewSocialServiceGateway(svc SocialService, hooks *twirp.ServerHooks) chi.Router {
        mux := chi.NewRouter()
        mux.Use(middleware.Logger)
        mux.Use(middleware.Timeout(5 * time.Second))
        mux.Mount("/twirp", NewSocialServiceServer(svc, hooks))
        return mux
}
~~~

But if the main RPC handlers would be a http.Handler I'd concievably do:

~~~go
        s := &socialServiceServer{svc, hooks}
        mux.Route("/twirp", func(r *chi.Router) {
                // selected public twirp subset of routes
        }
        mux.Route("/internal", func(r *chi.Router) {
                r.Get("/healthcheck", s.serveHealthcheck)
                // ...
        }
~~~

I'd also think it would be easier to add various policies like that (e.g. allow access to /internal only from LAN) etc.; I haven't looked into particular Twirp Authorization/Authentication patterns, yet, but with standard http handlers, which is a prominent benefit of Twirp over gRPC, I can add on pretty much anything I want as http middleware. Having the calls be unexposed, satisfying http.HandlerFunc, would help a lot towards getting there.
