### ISSUE TITLE
Support for GRPC status package

### ISSUE THREAD

**Issue by skolodyazhnyy** [twitchtv/twirp#254]
Hey,

I'm trying out twirp to compliment my GRPC server. Unfortunately, all my [GRPC errors](https://godoc.org/google.golang.org/grpc/status) are showing up as internal in twirp. Is there chance GRPC errors can be supported by Twirp error handler? 

Twirp Server interface is compatible with interface generated for GRPC server, which is great. It takes around 5 seconds to create twirp server if you have GRPC server. But errors are not compatible at all, so now I have to re-write my server implementation or wrap it into some adapters 😓

**Comment by marioizquierdo** [comment]
This sounds interesting. Twirp was designed initially to be familiar to gRPC users, but not to be fully compatible. With the years, we found that not many users have the need to bridge them both. I would be curious about what type of issues you find. Please, provide more details about how would you envision converting errors to status codes, is that a client adapter? a service middleware?

**Comment by ofpiyush** [comment]
I believe we'd made a server hook to deal with it or something.

I no longer work at Verloop. Let me ask around and see if we can remember the solution we came up for this.

**Comment by dalchand** [comment]
Check this https://github.com/twitchtv/twirp/issues/161

**Comment by marioizquierdo** [comment]
Maybe the proposal for Twirp middleware/interceptors would help build an adapter for gRPC? #265
