### ISSUE TITLE
Address function not supported

### ISSUE THREAD

**Issue by cannon73** [twitchtv/twirp#260]
I have some doubts about the T.W.I.R.P. software. It is similar to gRPC but does not support the gRPC way to read the I.P. Address of the client. If you are using T.W.I.R.P. without a proxy in front, would that not be a problem because you can not log where clients are coming from? Kindly include my solution to support the gRPC  I.P. Address function.

[peer.zip](https://github.com/twitchtv/twirp/files/5064873/peer.zip)

**Comment by marioizquierdo** [comment]
I'm not sure I understand your question, but Go Twirp Clients accept a `HTTPClient` where the `.Do` method is invoked. You can provide a `http.DefaultClient` like in the examples from the docs, but you can also provide a modified client to include origin headers or whatever you need, or a custom implementation. Twirp does not decide what to do with HTTP headers (besides Content-Type), but it tries to make it easy to provide your own client. We can work some examples in this issue if you think they will be useful to other developers. Please provide more details.
