### ISSUE TITLE
detecting import paths is incorrect for root vanity imports

### ISSUE THREAD

**Issue by marwan-at-work** [twitchtv/twirp#280]
Perhaps the comment in this line of code describes the issue best: https://github.com/twitchtv/twirp/blob/ead44db746049716fda1702d896ebdc2db1e898b/protoc-gen-twirp/go_naming.go#L34

An import path may not actually have a slash in it. For example if you define a vanity import such as "go.mycompany.com" and then define your protobuf file at the root of the module as such: 

```protobuf
syntax = "proto3";
package mycompany;
option go_package = "go.mycompany.com;mycompany";

...
```

Twirp will end up generating the following Go package declaration: 

```go
package go_mycompany_com_mycompany

...
```

This is clearly incorrect. Twirp should instead see if there's a semi-colon in the go_package option and then return the left hand side as the import path and the right hand side as the package name.

**Comment by amcohen-twitch** [comment]
Hi @marwan-at-work, thanks for bringing this to our attention. Our team was unaware of this expected behavior, and are having trouble finding documentation of it. By any chance, could you point us to any further details/docs?

**Comment by marwan-at-work** [comment]
@amcohen-twitch if try to generate Go code with `--go_out=.` with the latest protoc-gen-go (v2) and notice the warning it will spit out: 

```
2020/11/22 16:42:07 WARNING: Missing 'go_package' option in "dbregistry.proto",
please specify it with the full Go package path as
a future release of protoc-gen-go will require this be specified.
See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

So the docs it refers to is here: https://developers.google.com/protocol-buffers/docs/reference/go-generated#package
