### ISSUE TITLE
Haberdasher example generate warning.

### ISSUE THREAD

**Issue by zasdaym** [twitchtv/twirp#281]
I'm trying the Haberdasher example from Twirp documentation [here](https://twitchtv.github.io/twirp/docs/example.html), but the generated code shows warning on GoLand IDE. The code can be run, just curious the reason why it is a warning. I attached the related image.
![Screen Shot 2020-10-13 at 22 02 20](https://user-images.githubusercontent.com/18226580/95878811-d0dc6d00-0d9f-11eb-9bad-fe2326a68b33.png)

**Comment by 3ventic** [comment]
Scientific notation results in a float64 by default, but the compiler is smart enough to know that it is an int in this context. ([Playground example](https://play.golang.org/p/AGLkdvjadEy))

**Comment by amcohen-twitch** [comment]
Per @3ventic's comment, this appears to be an issue in Goland's hinting. Thanks for letting us know. Closing, as this doesn't appear to be a Twirp bug.
