### ISSUE TITLE
Twirp generates code that uses deprecated protobuf libraries

### ISSUE THREAD

**Issue by RoarkeRandall** [twitchtv/twirp#301]
Our team uses staticcheck, https://staticcheck.io, for linting our go programs. It's convenient to run `staticcheck ./...` on a repo in our ci pipelines. We are getting the following errors for the generated twirp code:

```
pkg/go/service.twirp.go:21:8: package github.com/golang/protobuf/jsonpb is deprecated: Use the "google.golang.org/protobuf/encoding/protojson" package instead.  (SA1019)
pkg/go/service.twirp.go:22:8: package github.com/golang/protobuf/proto is deprecated: Use the "google.golang.org/protobuf/proto" package instead.  (SA1019)
```

We are able to ignore these at a file level, but it requires us to manually add a line of code to the top of the generated file. Obviously editing generated code isn't a great solution. 

Is it possible for twirp to update the generated code to use the latest protobuf packages?

**Comment by mfridman** [comment]
The long-term solution is for twirp to update to the new protobuf packages. But, its also a limitation of statickcheck (see this issue and [comment](https://github.com/dominikh/go-tools/issues/429#issuecomment-713267008)).

It takes time for the ecosystem/community to update open-source projects, and statickcheck takes a very all/none approach.

We just ended up with a very unideal situation..

```
checks = [..., "-SA1019"]
```

I know this doesn't help you @RoarkeRandall, but you're not alone.

**Comment by 3ventic** [comment]
See also #222.

**Comment by 3ventic** [comment]
Twirp v8 generates clients using the new protobuf packages. Refer to the [release](https://github.com/twitchtv/twirp/releases/tag/v8.0.0) for the quick upgrade instructions.
