### ISSUE TITLE
Integration with vtprotobuf

### ISSUE THREAD

**Issue by T-J-L** [twitchtv/twirp#327]
I’m currently using twirp and have been exploring [vtprotobuf](https://github.com/planetscale/vtprotobuf) to generate optimized Marshal
/Unmarshal methods for proto messages. 

To modify a twirp file to use vtproto is simple. An example code change would be to change...
```go
respBytes, err := proto.Marshal(respContent)
``` 
to...
```go
respBytes, err := respContent.MarshalVT()
```
The equivalent can be done with Unmarshal. I've currently done this with a find and replace, with good results. 

Is integration with vtprotobuf something that could be considered as a code generation option? If so, I’m happy to make the changes.

**Comment by T-J-L** [comment]
And for completeness, the modifications to **doProtobufRequest**:

```go
	var reqBodyBytes []byte

	switch r := in.(type) {
	case *MyType:
		reqBodyBytes, err = r.MarshalVT()
		if err != nil {
			return ctx, wrapInternal(err, "failed to marshal proto request")
		}
	default:
		reqBodyBytes, err = proto.Marshal(in)
		if err != nil {
			return ctx, wrapInternal(err, "failed to marshal proto request")
		}
	}
```

```go
	switch r := out.(type) {
	case *MyType:
		if err = r.UnmarshalVT(respBodyBytes); err != nil {
			return ctx, wrapInternal(err, "failed to unmarshal proto response")
		}
	default:
		if err = proto.Unmarshal(respBodyBytes, out); err != nil {
			return ctx, wrapInternal(err, "failed to unmarshal proto response")
		}
	}
```

**Comment by 3ventic** [comment]
We generally try to avoid adding additional options or dependencies unless there's a compelling reason to do it. It sounds like a separate script to replace the calls in the Twirp-generated code would already accomplish this without issues; is that correct based on your testing with it?

**Comment by T-J-L** [comment]
That’s understandable. The find and replace option only applies to the server code, due to the generic marshalling code in the client. I had some time, so I’ve forked and applied the changes for both client and server code generation if you’re interested [here](https://github.com/T-J-L/twirp/pull/1/files). 

I’ll run benchmarks next week for my own workload but I expect it’s not worth maintaining a fork long-term.

**Comment by T-J-L** [comment]
Just to close this off, the performance benchmarks were significant, reducing all serialization time to about 40-50% of the reflection-based option. This is now up and running in production.

Just want to also point to https://github.com/twitchtv/twirp/issues/261 which I found; this solution would be a generic way of allowing users to implement custom marshalling.
