### ISSUE TITLE
UDS support? 

### ISSUE THREAD

**Issue by jordan-lumley** [twitchtv/twirp#333]
Hi there, 

Been spending the last couple of days doing some research into gRPC and twirp. Does twirp support Unix domain sockets? If so, is there any examples with using UDS?

**Comment by wmatveyenko** [comment]
Hi,
Twirp's support for Unix Domain Sockets would be the same as what net/http provides. Probably a combination of net.ListenUnix and net/http.Server.Serve would do the trick—but any guide for general net/http + UDS would apply.
