### ISSUE TITLE
Conformance test suite

### ISSUE THREAD

**Issue by Cyberax** [twitchtv/twirp#335]
I'm writing a C++ implementation of Twirp for our internal use ( https://github.com/Cyberax/twirp-cpp/ ) and one sticking point is the lack of interoperability/conformance tests.

Is there anyone interested in writing a spec for the tests and eventually the tests themselves?

**Comment by wmatveyenko** [comment]
Hi, thanks for you interest in Twirp. We do not plan to create a conformance test spec or suite of tests for other Twirp implementations, but would be happy to review any pull requests with those tests.

**Comment by marioizquierdo** [comment]
There is some basic interoperability-test functionality on the clientcompact folder: https://github.com/twitchtv/twirp/tree/main/clientcompat Maybe that is of any use?
