### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by craigpastro** [twitchtv/twirp#348]
👋 In the docs, on the "Usage Example: Haberdasher" page, the next link at the bottom, which should go to "Best Practices", is broken and leads to a 404. I had a look at how this could be fixed, but I am not very familiar with docusaurus, so I ended up giving up after some minutes. Sorry about that!

<img width="1196" alt="Screen Shot 2022-01-24 at 12 21 58 PM" src="https://user-images.githubusercontent.com/28915792/150858671-dce01c34-78c9-47b8-a88d-a78839de2c13.png">

**Comment by wmatveyenko** [comment]
Thanks. We regenerated the documentation site and this link should be fixed now.
