### ISSUE TITLE
Fasthttp support

### ISSUE THREAD

**Issue by pjebs** [twitchtv/twirp#366]

**Comment by wmatveyenko** [comment]
Hi, we would love to help, but we need a bit more detail 😉 .

**Comment by pjebs** [comment]
Can I make it work with fasthttp which is used behind the scenes in fibre framework?

**Comment by wmatveyenko** [comment]
Is there a reason why you feel it would not work? We don't specifically test with it, if that is the question you are asking.

**Comment by pjebs** [comment]
Fasthttp is an alternative to standard net/http package

**Comment by swiftyspiffy** [comment]
We need more details on specifically what changes you are suggesting and reasoning behind them. I recommend you checkout the code and test it against fasthttp and report back your findings (and potentially any problems you faced). I don't believe fasthttp has been brought up before by other users (beyond the reference [here](https://github.com/twitchtv/twirp/issues/166#issuecomment-479790093) around pooling).
