### ISSUE TITLE
Provide auto-instrumentation for OpenTelemetry standard

### ISSUE THREAD

**Issue by BrianGreenhill** [twitchtv/twirp#370]
First off, thanks so much for twirp!

The [OpenTelemetry](https://opentelemetry.io/) project has [a repo containing autoinstrumenters](https://github.com/open-telemetry/opentelemetry-go-contrib/tree/main/instrumentation) for widely used packages (like net/http and others). This issue is to track work on creating auto-instrumentation for twirp. I'm interested to hear your thoughts. Is this something you would be open to for this project?

**Comment by wmatveyenko** [comment]
Thanks for your interest. We would be open to OpenTelemetry support, but it is not something we would actively work on. What changes would it need for hooks / interceptors?

**Comment by BrianGreenhill** [comment]
It shouldn't require any changes to twirp itself. It can be implemented as a middleware in combination with a server hook. There are some examples in public repos already. One example: https://github.com/chengjiagan/twirp-opentelemetry/
