### ISSUE TITLE
Generated Code for sending JSON requests is not in the sending path

### ISSUE THREAD

**Issue by cloudsinmycoffee** [twitchtv/twirp#371]
Hello there! We're using the twirp library at work for sending/receiving JSON requests via http. It has come to our attention that the omitempty flag is not supported when it comes to sending JSON requests. For now, our solution is to patch it manually after the code is being generated. The bug seems to be in protoc-gen-twirp/generator.go at func doJSONRequest and should be adapted in line 824 from 

```
	t.P(`  marshaler := &`, t.pkgs["protojson"], `.MarshalOptions{UseProtoNames: true}`)
``` 
to 
```
	t.P(`  marshaler := &`, t.pkgs["protojson"], `.MarshalOptions{UseProtoNames: !s.jsonCamelCase, EmitUnpopulated: !s.jsonSkipDefaults}`)
```

Thanks in advance!

**Comment by wmatveyenko** [comment]
Hi, we happily accept pull requests if you would like to fix it.

**Comment by cloudsinmycoffee** [comment]
Sure thing, I created a pull request :)
