### ISSUE TITLE
Allow Interceptor to return *dynamicpb.Message

### ISSUE THREAD

**Issue by QuantumGhost** [twitchtv/twirp#382]
We're trying to write a generic interceptor that returning empty response to
client under specific circumstances. We have tried using [protobuf's reflection](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoreflect) to dynamic create a protobuf message with type [*dynamicpb.Message](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb#Message), and returning it to client without invoking the `next` handler.

However, The generated server code [does type assertion on the response returned from
interceptor](https://github.com/twitchtv/twirp/blob/main/example/service.twirp.go#L104-L110), so we cannot return `*dynamicpb.Message` directly from interceptor. The correspond generator code
is at [here](https://github.com/twitchtv/twirp/blob/main/protoc-gen-twirp/generator.go#L1468-L1474).

I'd like to know if there is any possibilty to remove the type assertion, or add support for `*dynamicpb.Message`.

**Comment by marioizquierdo** [comment]
A [Twirp interceptor](https://pkg.go.dev/github.com/twitchtv/twirp#Interceptor) is defined as a function that wraps a `Method` with another `Method`:

```go
type Interceptor func(Method) Method
type Method func(ctx context.Context, request interface{}) (response interface{}, err error)
```

But a Twirp service interface uses specific struct types. The `Method` response needs to be converted to a struct comehow.

```go
func (s *TwirpImpl) MyMethod(ctx context.Context, req *MyReq) (*MyResp, error) {
   // call interceptor
   respInterface, err := interceptor(next)(ctx, req)

   // we need to convert the respInterface interface{} into *MyResp
   // >> is this possible from a *dynamicpb.Message ??
   resp := respInterface.(*MyResp)

   return resp, err
}
```

**Comment by QuantumGhost** [comment]
No, as far as I know, It's not possible to cast `*dynamicpb.Message` back to concrete `proto.Message` implementations. 

However, the `proto.Marshal` / `protojson.Marshal` do work for `*dynamicpb.Message`. 

I'll check gRPC and similar projects to see how they handle similar cases.
