### ISSUE TITLE
Deprecated usage of `ioutil`

### ISSUE THREAD

**Issue by remko** [twitchtv/twirp#383]
[staticcheck](https://staticcheck.dev) reports that generated Twirp code uses the now deprecated `ioutil`:

    myfile.twirp.go:9:15: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details.  (SA1019)

What is the minimum supported version of the generator? If it's Go 1.16, then this issue can be fixed by generating better code. If not, would it be accepted to add a lint ignore header to the generated files? (since that's the only way to make staticcheck stop reporting this error)

**Comment by rakateja** [comment]
hi @remko could you also explain how to replicate this issue? I tried to take a look at my twirp-generated files, but I can't find this issue. Thank you

**Comment by remko** [comment]
@rakateja You're right, it was fixed in more recent versions of Twirp. Thanks.
