### ISSUE TITLE
Documentation website domain triggers Chrome's warning 

### ISSUE THREAD

**Issue by riprsa** [twitchtv/twirp#390]
<img width="673" alt="image" src="https://github.com/twitchtv/twirp/assets/44776391/76a18aaf-3f09-406f-831f-78cfbdd6ad20">

Docs website, of course, is: https://twitchtv.github.io/twirp/

I hope it is possible to contact Google from your side and fix this 😅

**Comment by swiftyspiffy** [comment]
We're aware of this issue and tracking internally. No progress yet, but definitely known.

**Comment by swiftyspiffy** [comment]
https://issuetracker.google.com/issues/342242650
```
Thank you for submitting your submission. We have successfully fetched and processed your digital asset link manifests across the following domains:
  * twitch.tv
  * twitchtv.github.io

Within a few days, lookalike warnings should stop showing on these sites. If you're still seeing the warnings in 1 week, feel free to follow-up here.
```

Will leave this open until issue is confirmed gone.

**Comment by swiftyspiffy** [comment]
Confirmed the issue is no longer present. Closing.
