### ISSUE TITLE
Add context metadata to generated client's request context

### ISSUE THREAD

**Issue by mkabischev** [twitchtv/twirp#45]
Hi, can you suggest what load balancing/service discovery strategies do you use in twitch? 
As I see the current implementation of twirp allows only to use server-side discovery using some reverse-proxy like ELB, nginx, hproxy, etc. But it will be great to have the possibility to use client-side discovery as well. 
It becomes easier to implement it with #39 because I can replace URL with the discovered host in the request. So imagine I can write some custom implementation of `HTTPClient` interface or `http.RoundTripper` like:

```go
// ClientWithDiscovery is an implementation of HTTPClient interface that automatically discovers services' hosts using consul/etcd/...
type ClientWithDiscovery struct {
   service string
   client    HTTPClient
}

func (c *ClientWithDiscovery) Do(r *http.Request) (*http.Response, error) {
    r.URL.Host = c.pickHostForService()
    return c.client.Do(r)       
}
```

The big problem of such implementation is that service is a property of the client and I have to create separate client for each service I want to use. But it can be easily solved if in request's context there will be information about service. Client generated code can contain lines like:
```go
func (c *haberdasherJSONClient) MakeHat(ctx context.Context, in *Size) (*Hat, error) {
        ctx = ctxsetters.WithServiceName(ctx, "Haberdasher") // <-- new line
	url := c.urlBase + HaberdasherPathPrefix + "MakeHat"
	out := new(Hat)
	err := doJSONRequest(ctx, c.client, url, in, out)
	return out, err
}
```

So then I can call `twirp.ServiceName(ctx)` in my new client to fetch service name and make discovery. 

What do you think?

**Comment by spenczar** [comment]
Service discovery and load balancing are _not_ something Twirp wants to have an opinion on. We'd prefer to plug in to whatever you use.

I agree that #39 will make this easier, and I also agree that setting context values in the client is now valuable.

I think we want more than just `WithServiceName`; we should call `WithMethodName` and `WithPackageName` too.

**Comment by robbawebba** [comment]
@spenczar I would love to help out with this feature if it is still available! This will be my first contribution to a large go project, so if you don't mind I might reach out to you on slack for some help if I get stuck 😅

**Comment by mkabischev** [comment]
@robbawebba, sorry man, I've already created PR :)

**Comment by robbawebba** [comment]
@mkabischev ahh sounds good. If you could comment on the issues you're working on in the future, I (and possibly other community members) would really appreciate it! thanks 🙂

**Comment by spenczar** [comment]
@robbawebba, PR #49 hasn't seen any movement in a week, so feel free to take a crack if you'd still like to!

**Comment by robbawebba** [comment]
Thanks @spenczar! If it's cool with you, I'll create a separate PR later since #49 is comparing from the other developer's fork.

**Comment by spenczar** [comment]
Sounds good to me @robbawebba.
