### ISSUE TITLE
Use Continuous build/test of some kind

### ISSUE THREAD

**Issue by cep21** [twitchtv/twirp#5]
Would using circle-ci or travis for the repository help?  It would allow people to submit pull requests and see the build result of them in the github UI.

**Comment by spenczar** [comment]
Yes, we should definitely do this right away. Just haven't gotten around to it in the conversion from a private project to a public one.

**Comment by hyandell** [comment]
Make sure you're checking the permissions they are asking for. Your GitHub org should have "Third-party application access policy=Access restricted". Travis CI (not Travis CI Private) is a good one.

**Comment by spenczar** [comment]
Fixed in #25.
