### ISSUE TITLE
Is it possible to get access to the *http.Request on the server?

### ISSUE THREAD

**Issue by polds** [twitchtv/twirp#50]
I've been playing around with trying to get Twirp running on App Engine Standard. Technically it works, but to call any methods in the appengine package you need an [appengine.Context](https://godoc.org/google.golang.org/appengine#NewContext) which can only be created using the http.Request object. 

So, any thoughts on if its possible to get the Request object?

**Comment by nawuko** [comment]
This question was asked on Slack recently. The owner of slack answered this with the following:

> The simplest option is HTTP middleware:
> ```
> func InjectAppengineContext(base http.Handler) http.Handler {
>   return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
>     r = r.WithContext(appengine.NewContext(r))
>     base.ServeHTTP(w, r)
>   })
> }
> ```
> you'd wrap the generated server with that middleware before actually mounting it on a listener, for example:  
> ```
> s := NewAuthServer(...)
> http.ListenAndServe("host:port", InjectAppengineContext(s))
> ```
> does that answer your question? like i mentioned, I'm a bit fuzzy on appengine and how this context thinger is supposed to be used

Hope i could help .... and spenczar dosent mind i copied his chat :see_no_evil:

**Comment by spenczar** [comment]
Righto - HTTP middleware is the best way to go about this sort of thing. I think it's good to keep the raw Request hidden from the Twirp server.

**Comment by EVILoptimist** [comment]
So, am I missing something? Or is there another (probably obvious?) way to access things like `r.Referer()`, `r.UserAgent()`, and `r.RemoteAddr`?

I can't figure out where they might be passed in the context. Or otherwise accessible.

**Comment by spenczar** [comment]
@EVILoptimist You can do that by passing them into the context yourself through HTTP middleware. See https://twitchtv.github.io/twirp/docs/headers.html#read-http-headers-from-requests.

For example, if you wanted `r.RemoteAddr` to be available:

```
var remoteAddrKey = new(int)

func RemoteAddr(ctx context.Context) string {
  return ctx.Value(remoteAddrKey).(string)
}

func WithRemoteAddr(base http.Handler) http.Handler {
  return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
    ctx := r.Context()
    ctx = context.WithValue(remoteAddrKey, r.RemoteAddr)
    r = r.WithContext(ctx)
    base.ServeHTTP(w, r)
  })
}
```

Now, wherever you're assembling your `http.Handler` (probably `package main`), you'd wrap the twirp server with that middleware:

```
app := NewHaberdasherImplementation()
s := example.NewHaberdasherServer(app, nil)

h := WithRemoteAddr(s)
http.ListenAndServe(":8080", h)
```

Now, requests that come in are passed through the `WithRemoteAddr` wrapper, which pulls values out of the `*http.Request` and stores them in `*http.Request.Context()`, which is the context that will be passed to your service implementation's methods.
