### ISSUE TITLE
go get failing: loc.GetLeadingDetachedComments undefined (type *descriptor.SourceCodeInfo_Location has no field or method GetLeadingDetachedComments)

### ISSUE THREAD

**Issue by Dieterbe** [twitchtv/twirp#57]
```
~ ❯❯❯ go get github.com/twitchtv/twirp/protoc-gen-twirp
# github.com/twitchtv/twirp/internal/gen/typemap
go/src/github.com/twitchtv/twirp/internal/gen/typemap/typemap.go:270:25: loc.GetLeadingDetachedComments undefined (type *descriptor.SourceCodeInfo_Location has no field or method GetLeadingDetachedComments)

```

**Comment by spenczar** [comment]
Yeah, we might need to commit a vendor directory in `protoc-gen-twirp` to help with this.

Your immediate problem will be resolved by updating `github.com/golang/protobuf/protoc-gen-go/descriptor`'s version in your GOPATH, @dieterbe. Run `go get -u github.com/golang/protobuf/protoc-gen-go/descriptor`.

**Comment by Dieterbe** [comment]
Hi Spencer,
that works fine. thanks!
