### ISSUE TITLE
Typo in client usage wiki page

### ISSUE THREAD

**Issue by jcomo** [twitchtv/twirp#6]
Not sure how to PR wikis, but there is a typo in the usage of the client code. I believe the [last section](https://github.com/twitchtv/twirp/wiki/Usage-Example:-Haberdasher#using-twirp-clients) should have this error handling code since the current code doesn't compile.

```go
if err != nil {
    twerr, ok := err.(twirp.Error)
    if ok {
        switch twerr.Code() {
        case twirp.InvalidArgument:
            fmt.Println("Oh no "+twerr.Msg())
        default:
            fmt.Println(twerr.Error())
        }
    }
    return
}
```

**Comment by spenczar** [comment]
Thanks, fixed.
