### ISSUE TITLE
Typo on Errors wiki page

### ISSUE THREAD

**Issue by achille-roussel** [twitchtv/twirp#67]
Hello,

On the [Errors](https://github.com/twitchtv/twirp/wiki/Errors) wiki package there's a typo:
- https://github.comm/twitchtv/twirp/blob/master/errors.go
should be
- https://github.com/twitchtv/twirp/blob/master/errors.go (.com and not .comm)
which means the link is dead.

I couldn't find a way to submit a pull request for the wiki repository so I'm opening an issue. Let me know if there's a better way.

Cheers!

**Comment by rhysh** [comment]
Fixed, thanks Achille
