### ISSUE TITLE
urlBase fails if the address has no scheme

### ISSUE THREAD

**Issue by achille-roussel** [twitchtv/twirp#68]
Hi all,

The generated `urlBase` function doesn't seem to be working as intended, or the `New{Service}ProtobufClient` documentation needs to be updated.

Here's a small program highlighting the problem:
```go
package main

import (
	"fmt"
	"net/url"
)

// this is a copy of urlBase as found in .twirp.go files
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

func main() {
	const addr = "127.0.0.1:1234"
	fmt.Println(urlBase(addr))
	fmt.Println(url.Parse(addr))
}
```
```
127.0.0.1:1234
<nil> parse 127.0.0.1:1234: first path segment in URL cannot contain colon
```
The problem is when the HTTP request is constructed, it needs a scheme (either http:// or https://) or it fails with the same error, because it mistakens the IP:port pair for a path in the URL.

Prefixing the address with "http://" when instantiating the client worked fine.

This was confusing and hard to track down tho, I suggest we do one of the following:
- Document the `New{Service}ProtobufClient` function to mention that the address must have a scheme (which means the `urlBase` function could go away)
- Modify the `urlBase` function to not rely on `url.Parse`, maybe just look for a `://` sequence instead.

Let me know what you think would be best, or if you have other recommendations, I can take care of submitting a PR.

**Comment by rhysh** [comment]
`url.Parse` expects an input like "//127.0.0.1:1234" to mean there's no scheme. That input would work today, but it doesn't seem like the best interface to provide—particularly for a parameter called "addr").

We need to let users specify the scheme, host, and port—without implying that they can set a path prefix, query, or fragment. We don't have appropriate validation there today. I think it's wrong for `urlBase` to return a value that will trigger problems later when passed to `http.NewRequest`.

If it needs to return an error, it should come up with a good error and find a way to get it back to the user. (That might mean shoving it into a field on the generated client, and having all methods return the error if one is set.)

@spenczar can you specify the right behavior here by giving a list of inputs and desired results? Here's a stab:

```
"127.0.0.1:1234" -> ???
"//127.0.0.1:1234" -> ???

"http://127.0.0.1:1234"  -> http, 127.0.0.1, 1234
"http://127.0.0.1"       -> http, 127.0.0.1, 80
"https://127.0.0.1:1234" -> https, 127.0.0.1, 1234
"https://127.0.0.1"      -> https, 127.0.0.1, 443

"http://127.0.0.1:1234/" -> http, 127.0.0.1, 1234

"http://127.0.0.1:1234/nope"  -> ???
"http://127.0.0.1:1234?no=pe" -> ???
"http://127.0.0.1:1234#nope"  -> ???
```

**Comment by spenczar** [comment]
@rhysh, I really don't want to have to return an error here. I'd rather do the right thing for the common case. So, supporting `host:port` is obviously important here. I am really unconcerned with our level of support for anybody weird enough to write `//host:port`.

I'd prefer to think of the list of inputs and desired results in terms of string -> string. Our job is *just* to set the scheme to `http://` if it isn't set.

This is a slight change to our current behavior, as we'll provide a special case for `host:port` strings. That's fine with me, as they're so common.

So, in your table, here is what I want, expressed as string -> string.
```
"127.0.0.1:1234" -> "http://127.0.0.1:1234"
"//127.0.0.1:1234" -> "//127.0.0.1:1234"

"http://127.0.0.1:1234"  -> "http://127.0.0.1:1234"
"http://127.0.0.1"       -> "http://127.0.0.1"
"https://127.0.0.1:1234" -> "https://127.0.0.1:1234"
"https://127.0.0.1"      -> "https://127.0.0.1"

"http://127.0.0.1:1234/" -> "http://127.0.0.1:1234"

"http://127.0.0.1:1234/nope"  -> "http://127.0.0.1:1234/nope"
"http://127.0.0.1:1234?no=pe" -> "http://127.0.0.1:1234?no=pe"
"http://127.0.0.1:1234#nope"  -> "http://127.0.0.1:1234#nope"
```

> without implying that they can set a path prefix

I think we'd like to support a path prefix if/when we implement #55, to be clear.

**Comment by marioizquierdo** [comment]
The PR #264 implements optional prefixes for Twirp URLs. As part of the changes, the function `urlBase` was renamed to `sanitizeBaseURL`: https://github.com/twitchtv/twirp/pull/264/files#diff-a3a2b0741a88a528d33eb1f40bef6b04L443

That should clarify the intention a little bit. If the URL is invalid, it will fail with a clear error later when making requests.
