### ISSUE TITLE
Hooks for authentication and authorization

### ISSUE THREAD

**Issue by casoetan** [twitchtv/twirp#90]
Trying to use hooks for authentication and authorization does not seem possible as stated in the documentation, especially if auth token are present in the header of each request.

I'm using JWT with the token in the authorization header.

**Comment by spenczar** [comment]
Could you say more about why this isn't possible? We do this with two parts: HTTP middleware that puts headers into request contexts, and hooks that check them:
```golang
var jwtCtxKey = new(int)

func WithJWT(base http.Handler) http.Handler {
  return http.HandlerFunc(w http.ResponseWriter, r *http.Request) {
    jwt := getJWT(r) // Pulls the jwt out of the Authorization header, or something
    ctx := r.Context()
    if jwt != nil {
      ctx = context.WithValue(jwtCtxKey, jwt)
    }
    r = r.WithContext(ctx)
    base.ServeHTTP(w, r)
  }
}

func JWTCheckerHooks() *twirp.ServerHooks {
  hooks := &twirp.ServerHooks{}
  hooks.RequestRouted = func(ctx context.Context) (context.Context, error) {
    jwt, ok := ctx.Value(jwtCtxKey).(*jwt)
    if !ok {
      // jwt missing: either middleware wasn't run, or it wasnt in the req
      return nil, twirp.NewError(twirp.Unauthenticated, "jwt must be included")
    }
    svc, _ := twirp.ServiceName(ctx)
    method, _ := twirp.MethodName(ctx)
    if !authorized(jwt, svc, method) {
      return ctx, twirp.NewError(twirp.PermissionDenied, "not authorized to use this method")
    }
    return ctx, nil
  }
  return hooks
}
```

The HTTP middleware wraps your Twirp server; the JWT hooks are called by your server. So it ends up looking like this in `package main`:
```golang
func serve(app haberdasher.Haberdasher) {
  hooks := JWTCheckerHooks()
  var handler http.Handler = haberdasher.NewHaberdasherServer(app, hooks)
  handler = WithJWT(handler)
  http.ListenAndServe(":8080", handler)
}
```
---

That's how I use them. What's not working for you in this flow? Or was this flow not clear from the docs? I realize they are pretty sketchy on how you do this.

**Comment by casoetan** [comment]
Thanks @spenczar. Wasn't quite clear from the docs. I think this should be a second example to the statsd example.
