### ISSUE TITLE
Seeking feedback on protoc twirp typescript plugin

### ISSUE THREAD

**Issue by larrymyers** [twitchtv/twirp#93]
I've created a protoc twirp client generator that outputs fairly simple typescript.  I've already tested it out on a few personal projects and I've been happy with the amount of code I've been able to delete on the client and server.

I'm looking for feedback from the twirp team to see if it should be added to the list of codegen plugins in the twirp docs.

@spenczar this is the project I referenced in issue #84 , if you could take a few minutes to comment I'd appreciate the feedback to see if it's something that is useful for the general twirp community.

**Comment by spenczar** [comment]
Excellent! This looks really great, yes! Please, go ahead and submit a PR to add it to the list on the README. Thanks!

**Comment by slaskis** [comment]
It looks great, nice and simple! 

If anything I'd love if it was more extendable and maybe even no dependencies. If I could pass fetch as an option that would be nice, similar to how Apollo does it (so I can use isomorphic unfetch instead for instance). Also now i would have no control of retries etc without forking it. Perhaps a callback for the http request would be enough? With a clear default of what it is now

**Comment by larrymyers** [comment]
@slaskis That's a really good idea.  I'd like to continue to have an option that works out of the box for most people, but being able to inject in your own implementation of fetch makes sense.
